// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);

lv_obj_t *ui_Screen1;
lv_obj_t *ui_headerpn;
lv_obj_t *ui_silabslogoscr1;
lv_obj_t *ui_prjname0;
lv_obj_t *ui_inforpanel0;
lv_obj_t *ui_deviceinforlb0;
lv_obj_t *ui_maclb0;
lv_obj_t *ui_historylb0;
lv_obj_t *ui_deviceiconpn0;
lv_obj_t *ui_lightofficon0;
lv_obj_t *ui_tempicon0;
lv_obj_t *ui_butofficon0;
lv_obj_t *ui_butonicon0;
lv_obj_t *ui_lightonicon0;
lv_obj_t *ui_devicenamelb0;
void ui_event_removeicon0(lv_event_t *e);

lv_obj_t *ui_removeicon0;
lv_obj_t *ui_inforpanel1;
lv_obj_t *ui_maclb1;
lv_obj_t *ui_devicenamelb1;
void ui_event_removeicon1(lv_event_t *e);

lv_obj_t *ui_removeicon1;
lv_obj_t *ui_deviceiconpn1;
lv_obj_t *ui_lightofficon1;
lv_obj_t *ui_tempicon1;
lv_obj_t *ui_butofficon1;
lv_obj_t *ui_butonicon1;
lv_obj_t *ui_lightonicon1;
lv_obj_t *ui_historylb1;
lv_obj_t *ui_deviceinforlb1;
lv_obj_t *ui_inforpanel2;
lv_obj_t *ui_devicenamelb2;
lv_obj_t *ui_maclb2;
void ui_event_removeicon2(lv_event_t *e);

lv_obj_t *ui_removeicon2;
lv_obj_t *ui_deviceiconpn2;
lv_obj_t *ui_lightofficon2;
lv_obj_t *ui_tempicon2;
lv_obj_t *ui_butofficon2;
lv_obj_t *ui_butonicon2;
lv_obj_t *ui_lightonicon2;
lv_obj_t *ui_historylb2;
lv_obj_t *ui_deviceinforlb2;
lv_obj_t *ui_inforpanel3;
lv_obj_t *ui_devicenamelb3;
lv_obj_t *ui_maclb3;
void ui_event_removeicon3(lv_event_t *e);

lv_obj_t *ui_removeicon3;
lv_obj_t *ui_deviceiconpn3;
lv_obj_t *ui_lightofficon3;
lv_obj_t *ui_tempicon3;
lv_obj_t *ui_butofficon3;
lv_obj_t *ui_butonicon3;
lv_obj_t *ui_lightonicon3;
lv_obj_t *ui_historylb3;
lv_obj_t *ui_deviceinforlb3;
lv_obj_t *ui_inforpanel4;
lv_obj_t *ui_maclb4;
lv_obj_t *ui_devicenamelb4;
void ui_event_removeicon4(lv_event_t *e);

lv_obj_t *ui_removeicon4;
lv_obj_t *ui_deviceiconpn4;
lv_obj_t *ui_lightofficon4;
lv_obj_t *ui_tempicon4;
lv_obj_t *ui_butofficon4;
lv_obj_t *ui_butonicon4;
lv_obj_t *ui_lightonicon4;
lv_obj_t *ui_historylb4;
lv_obj_t *ui_deviceinforlb4;
lv_obj_t *ui_inforpanel5;
lv_obj_t *ui_devicenamelb5;
lv_obj_t *ui_maclb5;
void ui_event_removeicon5(lv_event_t *e);

lv_obj_t *ui_removeicon5;
lv_obj_t *ui_deviceiconpn5;
lv_obj_t *ui_lightofficon5;
lv_obj_t *ui_tempicon5;
lv_obj_t *ui_butofficon5;
lv_obj_t *ui_butonicon5;
lv_obj_t *ui_lightonicon5;
lv_obj_t *ui_historylb5;
lv_obj_t *ui_deviceinforlb5;
void ui_event_settingpn(lv_event_t *e);

lv_obj_t *ui_settingpn;
lv_obj_t *ui_settingicon;
void ui_event_tickpn0(lv_event_t *e);

lv_obj_t *ui_tickpn0;
lv_obj_t *ui_tickicon0;

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);

lv_obj_t *ui_Screen2;
lv_obj_t *ui_silabslogoscr2;
void ui_event_removedevpn(lv_event_t *e);

lv_obj_t *ui_removedevpn;
lv_obj_t *ui_removedevlb;
void ui_event_adddevpn(lv_event_t *e);

lv_obj_t *ui_adddevpn;
lv_obj_t *ui_adddevlb;
void ui_event_exitscr3pn2(lv_event_t *e);

lv_obj_t *ui_exitscr3pn2;
lv_obj_t *ui_exiticon2;

lv_obj_t *ui_warningpn;
lv_obj_t *ui_removewarninglb;
lv_obj_t *ui_warningicon;

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);

lv_obj_t *ui_Screen3;
void ui_event_devlistpn(lv_event_t *e);

lv_obj_t *ui_devlistpn;
void ui_event_devscannedpn0(lv_event_t *e);

lv_obj_t *ui_devscannedpn0;
lv_obj_t *ui_macdevlb0;
void ui_event_devscannedpn1(lv_event_t *e);

lv_obj_t *ui_devscannedpn1;
lv_obj_t *ui_macdevlb1;
void ui_event_devscannedpn2(lv_event_t *e);

lv_obj_t *ui_devscannedpn2;
lv_obj_t *ui_macdevlb2;
void ui_event_devscannedpn3(lv_event_t *e);

lv_obj_t *ui_devscannedpn3;
lv_obj_t *ui_macdevlb3;
void ui_event_devscannedpn4(lv_event_t *e);

lv_obj_t *ui_devscannedpn4;
lv_obj_t *ui_macdevlb4;
void ui_event_devscannedpn5(lv_event_t *e);

lv_obj_t *ui_devscannedpn5;
lv_obj_t *ui_macdevlb5;
lv_obj_t *ui_devlisttxt0;
lv_obj_t *ui_headerscr3;
lv_obj_t *ui_silabslogoscr3;
void ui_event_exitscr3pn(lv_event_t *e);

lv_obj_t *ui_exitscr3pn;
lv_obj_t *ui_exiticon;

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);

lv_obj_t *ui_Screen4;
lv_obj_t *ui_keyboardpn;
lv_obj_t *ui_Keyboard1;
void ui_event_setenckeytxtarea(lv_event_t *e);

lv_obj_t *ui_setenckeytxtarea;
void ui_event_setdevnametxtarea(lv_event_t *e);

lv_obj_t *ui_setdevnametxtarea;
lv_obj_t *ui_silabslogoscr4;
lv_obj_t *ui_deviceconfigpn;
lv_obj_t *ui_deviceconfigtxt;
lv_obj_t *ui_deviceconfigmac;
void ui_event_exitscr3pn1(lv_event_t *e);

lv_obj_t *ui_exitscr3pn1;
lv_obj_t *ui_exiticon1;
void ui_event_tickpn1(lv_event_t *e);

lv_obj_t *ui_tickpn1;
lv_obj_t *ui_tickicon;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_button_off_ic_[1] =
{ &ui_img_button_off_ic_1_png };
const lv_img_dsc_t *ui_imgset_button_on_icon_[1] =
{ &ui_img_button_on_icon_1_png };
const lv_img_dsc_t *ui_imgset_button_on_ic_[1] = { &ui_img_button_on_ic_1_png };
const lv_img_dsc_t *ui_imgset_light_on_icon_[1] =
{ &ui_img_light_on_icon_1_png };
const lv_img_dsc_t *ui_imgset_silabs_logo_[1] = { &ui_img_silabs_logo_2_png };

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_removeicon0(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    removeslot0cb(e);
  }
}

void ui_event_removeicon1(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    removeslot1cb(e);
  }
}

void ui_event_removeicon2(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    removeslot2cb(e);
  }
}

void ui_event_removeicon3(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    removeslot3cb(e);
  }
}

void ui_event_removeicon4(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    removeslot4cb(e);
  }
}

void ui_event_removeicon5(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    removeslot5cb(e);
  }
}

void ui_event_settingpn(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    seticonchangetosr2(e);
  }
}

void ui_event_tickpn0(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    removecompletecb(e);
  }
}

void ui_event_removedevpn(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    rmbacktoscr1(e);
  }
}

void ui_event_adddevpn(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    addnewchangetoscr3(e);
  }
}

void ui_event_exitscr3pn2(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    exitscr2toscr1(e);
  }
}

void ui_event_devlistpn(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    displaykeyboard(e);
  }
}

void ui_event_devscannedpn0(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    adddeviceslot0(e);
  }
}

void ui_event_devscannedpn1(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    adddeviceslot1(e);
  }
}

void ui_event_devscannedpn2(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    adddeviceslot2(e);
  }
}

void ui_event_devscannedpn3(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    adddeviceslot3(e);
  }
}

void ui_event_devscannedpn4(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    adddeviceslot4(e);
  }
}

void ui_event_devscannedpn5(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    adddeviceslot5(e);
  }
}

void ui_event_exitscr3pn(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    exitsc3backtosc2(e);
  }
}

void ui_event_setenckeytxtarea(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    _ui_keyboard_set_target(ui_Keyboard1, ui_setenckeytxtarea);
  }
}

void ui_event_setdevnametxtarea(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    _ui_keyboard_set_target(ui_Keyboard1, ui_setdevnametxtarea);
  }
}

void ui_event_exitscr3pn1(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    exitsc4backtosc3(e);
  }
}

void ui_event_tickpn1(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;
  if (event_code == LV_EVENT_CLICKED) {
    registercompletecb(e);
  }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
  lv_disp_t *dispp = lv_disp_get_default();
  lv_theme_t *theme =
    lv_theme_default_init(dispp,
                          lv_palette_main(LV_PALETTE_BLUE),
                          lv_palette_main(LV_PALETTE_RED),
                          false,
                          LV_FONT_DEFAULT);
  lv_disp_set_theme(dispp, theme);
  ui_Screen1_screen_init();
  ui_Screen2_screen_init();
  ui_Screen3_screen_init();
  ui_Screen4_screen_init();
  ui____initial_actions0 = lv_obj_create(NULL);
  lv_disp_load_scr(ui_Screen1);
}
