// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);

extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_headerpn;
extern lv_obj_t *ui_silabslogoscr1;
extern lv_obj_t *ui_prjname0;
extern lv_obj_t *ui_inforpanel0;
extern lv_obj_t *ui_deviceinforlb0;
extern lv_obj_t *ui_maclb0;
extern lv_obj_t *ui_historylb0;
extern lv_obj_t *ui_deviceiconpn0;
extern lv_obj_t *ui_lightofficon0;
extern lv_obj_t *ui_tempicon0;
extern lv_obj_t *ui_butofficon0;
extern lv_obj_t *ui_butonicon0;
extern lv_obj_t *ui_lightonicon0;
extern lv_obj_t *ui_devicenamelb0;
void ui_event_removeicon0(lv_event_t *e);

extern lv_obj_t *ui_removeicon0;
extern lv_obj_t *ui_inforpanel1;
extern lv_obj_t *ui_maclb1;
extern lv_obj_t *ui_devicenamelb1;
void ui_event_removeicon1(lv_event_t *e);

extern lv_obj_t *ui_removeicon1;
extern lv_obj_t *ui_deviceiconpn1;
extern lv_obj_t *ui_lightofficon1;
extern lv_obj_t *ui_tempicon1;
extern lv_obj_t *ui_butofficon1;
extern lv_obj_t *ui_butonicon1;
extern lv_obj_t *ui_lightonicon1;
extern lv_obj_t *ui_historylb1;
extern lv_obj_t *ui_deviceinforlb1;
extern lv_obj_t *ui_inforpanel2;
extern lv_obj_t *ui_devicenamelb2;
extern lv_obj_t *ui_maclb2;
void ui_event_removeicon2(lv_event_t *e);

extern lv_obj_t *ui_removeicon2;
extern lv_obj_t *ui_deviceiconpn2;
extern lv_obj_t *ui_lightofficon2;
extern lv_obj_t *ui_tempicon2;
extern lv_obj_t *ui_butofficon2;
extern lv_obj_t *ui_butonicon2;
extern lv_obj_t *ui_lightonicon2;
extern lv_obj_t *ui_historylb2;
extern lv_obj_t *ui_deviceinforlb2;
extern lv_obj_t *ui_inforpanel3;
extern lv_obj_t *ui_devicenamelb3;
extern lv_obj_t *ui_maclb3;
void ui_event_removeicon3(lv_event_t *e);

extern lv_obj_t *ui_removeicon3;
extern lv_obj_t *ui_deviceiconpn3;
extern lv_obj_t *ui_lightofficon3;
extern lv_obj_t *ui_tempicon3;
extern lv_obj_t *ui_butofficon3;
extern lv_obj_t *ui_butonicon3;
extern lv_obj_t *ui_lightonicon3;
extern lv_obj_t *ui_historylb3;
extern lv_obj_t *ui_deviceinforlb3;
extern lv_obj_t *ui_inforpanel4;
extern lv_obj_t *ui_maclb4;
extern lv_obj_t *ui_devicenamelb4;
void ui_event_removeicon4(lv_event_t *e);

extern lv_obj_t *ui_removeicon4;
extern lv_obj_t *ui_deviceiconpn4;
extern lv_obj_t *ui_lightofficon4;
extern lv_obj_t *ui_tempicon4;
extern lv_obj_t *ui_butofficon4;
extern lv_obj_t *ui_butonicon4;
extern lv_obj_t *ui_lightonicon4;
extern lv_obj_t *ui_historylb4;
extern lv_obj_t *ui_deviceinforlb4;
extern lv_obj_t *ui_inforpanel5;
extern lv_obj_t *ui_devicenamelb5;
extern lv_obj_t *ui_maclb5;
void ui_event_removeicon5(lv_event_t *e);

extern lv_obj_t *ui_removeicon5;
extern lv_obj_t *ui_deviceiconpn5;
extern lv_obj_t *ui_lightofficon5;
extern lv_obj_t *ui_tempicon5;
extern lv_obj_t *ui_butofficon5;
extern lv_obj_t *ui_butonicon5;
extern lv_obj_t *ui_lightonicon5;
extern lv_obj_t *ui_historylb5;
extern lv_obj_t *ui_deviceinforlb5;
void ui_event_settingpn(lv_event_t *e);

extern lv_obj_t *ui_settingpn;
extern lv_obj_t *ui_settingicon;
void ui_event_tickpn0(lv_event_t *e);

extern lv_obj_t *ui_tickpn0;
extern lv_obj_t *ui_tickicon0;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);

extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_silabslogoscr2;
void ui_event_removedevpn(lv_event_t *e);

extern lv_obj_t *ui_removedevpn;
extern lv_obj_t *ui_removedevlb;
void ui_event_adddevpn(lv_event_t *e);

extern lv_obj_t *ui_adddevpn;
extern lv_obj_t *ui_adddevlb;
void ui_event_exitscr3pn2(lv_event_t *e);

extern lv_obj_t *ui_exitscr3pn2;
extern lv_obj_t *ui_exiticon2;

extern lv_obj_t *ui_warningpn;
extern lv_obj_t *ui_removewarninglb;
extern lv_obj_t *ui_warningicon;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);

extern lv_obj_t *ui_Screen3;
void ui_event_devlistpn(lv_event_t *e);

extern lv_obj_t *ui_devlistpn;
void ui_event_devscannedpn0(lv_event_t *e);

extern lv_obj_t *ui_devscannedpn0;
extern lv_obj_t *ui_macdevlb0;
void ui_event_devscannedpn1(lv_event_t *e);

extern lv_obj_t *ui_devscannedpn1;
extern lv_obj_t *ui_macdevlb1;
void ui_event_devscannedpn2(lv_event_t *e);

extern lv_obj_t *ui_devscannedpn2;
extern lv_obj_t *ui_macdevlb2;
void ui_event_devscannedpn3(lv_event_t *e);

extern lv_obj_t *ui_devscannedpn3;
extern lv_obj_t *ui_macdevlb3;
void ui_event_devscannedpn4(lv_event_t *e);

extern lv_obj_t *ui_devscannedpn4;
extern lv_obj_t *ui_macdevlb4;
void ui_event_devscannedpn5(lv_event_t *e);

extern lv_obj_t *ui_devscannedpn5;
extern lv_obj_t *ui_macdevlb5;
extern lv_obj_t *ui_devlisttxt0;
extern lv_obj_t *ui_headerscr3;
extern lv_obj_t *ui_silabslogoscr3;
void ui_event_exitscr3pn(lv_event_t *e);

extern lv_obj_t *ui_exitscr3pn;
extern lv_obj_t *ui_exiticon;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);

extern lv_obj_t *ui_Screen4;
extern lv_obj_t *ui_keyboardpn;
extern lv_obj_t *ui_Keyboard1;
void ui_event_setenckeytxtarea(lv_event_t *e);

extern lv_obj_t *ui_setenckeytxtarea;
void ui_event_setdevnametxtarea(lv_event_t *e);

extern lv_obj_t *ui_setdevnametxtarea;
extern lv_obj_t *ui_silabslogoscr4;
extern lv_obj_t *ui_deviceconfigpn;
extern lv_obj_t *ui_deviceconfigtxt;
extern lv_obj_t *ui_deviceconfigmac;
void ui_event_exitscr3pn1(lv_event_t *e);

extern lv_obj_t *ui_exitscr3pn1;
extern lv_obj_t *ui_exiticon1;
void ui_event_tickpn1(lv_event_t *e);

extern lv_obj_t *ui_tickpn1;
extern lv_obj_t *ui_tickicon;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1228364278);    // assets\silabs_logo-removebg.png
LV_IMG_DECLARE(ui_img_query_icon_png);    // assets\query_icon.png
LV_IMG_DECLARE(ui_img_light_off_icon_png);    // assets\light_off_icon.png
LV_IMG_DECLARE(ui_img_temperature_icon_png);    // assets\temperature_icon.png
LV_IMG_DECLARE(ui_img_button_off_ic_1_png);    // assets\button_off_ic_1.png
LV_IMG_DECLARE(ui_img_button_on_ic_1_png);    // assets\button_on_ic_1.png
LV_IMG_DECLARE(ui_img_light_on_icon_1_png);    // assets\light_on_icon_1.png
LV_IMG_DECLARE(ui_img_rm_icon_png);    // assets\rm_icon.png
LV_IMG_DECLARE(ui_img_setting_icon_png);    // assets\setting_icon.png
LV_IMG_DECLARE(ui_img_tick_icon_png);    // assets\tick_icon.png
LV_IMG_DECLARE(ui_img_exit_icon_png);    // assets\exit_icon.png
LV_IMG_DECLARE(ui_img_warning_icon_png);    // assets\warning_icon.png
LV_IMG_DECLARE(ui_img_button_on_icon_1_png);    // assets\button_on_icon_1.png
LV_IMG_DECLARE(ui_img_silabs_logo_2_png);    // assets\silabs_logo_2.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
