// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

extern bool register_completed;
extern uint8_t remove_slot;
extern bool remove_completed;

void removeslot0cb(lv_event_t *e);
void removeslot1cb(lv_event_t *e);
void removeslot2cb(lv_event_t *e);
void removeslot3cb(lv_event_t *e);
void removeslot4cb(lv_event_t *e);
void removeslot5cb(lv_event_t *e);
void seticonchangetosr2(lv_event_t *e);
void removecompletecb(lv_event_t *e);
void rmbacktoscr1(lv_event_t *e);
void addnewchangetoscr3(lv_event_t *e);
void exitscr2toscr1(lv_event_t *e);
void displaykeyboard(lv_event_t *e);
void adddeviceslot0(lv_event_t *e);
void adddeviceslot1(lv_event_t *e);
void adddeviceslot2(lv_event_t *e);
void adddeviceslot3(lv_event_t *e);
void adddeviceslot4(lv_event_t *e);
void adddeviceslot5(lv_event_t *e);
void exitsc3backtosc2(lv_event_t *e);
void exitsc4backtosc3(lv_event_t *e);
void registercompletecb(lv_event_t *e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
