// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

static char *mac;
bool register_completed = true;
uint8_t remove_slot = 0xFF;
bool remove_completed = true;

void seticonchangetosr2(lv_event_t *e)
{
  (void)e;

  lv_disp_load_scr(ui_Screen2);
}

void rmbacktoscr1(lv_event_t *e)
{
  (void)e;

  remove_completed = false;
  lv_disp_load_scr(ui_Screen1);
  lv_obj_clear_flag(ui_removeicon0, LV_OBJ_FLAG_HIDDEN);
  lv_obj_clear_flag(ui_removeicon1, LV_OBJ_FLAG_HIDDEN);
  lv_obj_clear_flag(ui_removeicon2, LV_OBJ_FLAG_HIDDEN);
  lv_obj_clear_flag(ui_removeicon3, LV_OBJ_FLAG_HIDDEN);
  lv_obj_clear_flag(ui_removeicon4, LV_OBJ_FLAG_HIDDEN);
  lv_obj_clear_flag(ui_removeicon5, LV_OBJ_FLAG_HIDDEN);
  lv_obj_clear_flag(ui_tickpn0, LV_OBJ_FLAG_HIDDEN);
  lv_obj_clear_flag(ui_settingpn, LV_OBJ_FLAG_CLICKABLE);
  lv_obj_set_x(ui_settingpn, 29);
  lv_obj_set_y(ui_settingpn, 219);
}

void addnewchangetoscr3(lv_event_t *e)
{
  (void)e;

  lv_disp_load_scr(ui_Screen3);
}

void backtohomescr(lv_event_t *e)
{
  (void)e;

  lv_disp_load_scr(ui_Screen1);
}

void displaykeyboard(lv_event_t *e)
{
  (void)e;

  lv_obj_clear_flag(ui_keyboardpn, LV_OBJ_FLAG_HIDDEN);
}

void exitscr2toscr1(lv_event_t *e)
{
  (void)e;

  lv_disp_load_scr(ui_Screen1);
}

void exitsc3backtosc2(lv_event_t *e)
{
  (void)e;

  lv_disp_load_scr(ui_Screen2);
}

void exitsc4backtosc3(lv_event_t *e)
{
  (void)e;

  lv_disp_load_scr(ui_Screen3);
  lv_textarea_clear_selection(ui_setdevnametxtarea);
  lv_textarea_clear_selection(ui_setenckeytxtarea);
}

void adddeviceslot0(lv_event_t *e)
{
  (void)e;

  lv_textarea_set_text(ui_setenckeytxtarea, "12345678123456781234567812345678");
  lv_textarea_set_text(ui_setdevnametxtarea, "BTHOME");
  if (!lv_obj_has_flag(ui_macdevlb0, LV_OBJ_FLAG_HIDDEN)) {
    mac = lv_label_get_text(ui_macdevlb0);
    lv_label_set_text(ui_deviceconfigmac, mac);
    lv_disp_load_scr(ui_Screen4);
  }
}

void adddeviceslot1(lv_event_t *e)
{
  (void)e;

  if (!lv_obj_has_flag(ui_macdevlb1, LV_OBJ_FLAG_HIDDEN)) {
    mac = lv_label_get_text(ui_macdevlb1);
    lv_label_set_text(ui_deviceconfigmac, mac);
    lv_disp_load_scr(ui_Screen4);
  }
}

void adddeviceslot2(lv_event_t *e)
{
  (void)e;

  if (!lv_obj_has_flag(ui_macdevlb2, LV_OBJ_FLAG_HIDDEN)) {
    mac = lv_label_get_text(ui_macdevlb2);
    lv_label_set_text(ui_deviceconfigmac, mac);
    lv_disp_load_scr(ui_Screen4);
  }
}

void adddeviceslot3(lv_event_t *e)
{
  (void)e;

  if (!lv_obj_has_flag(ui_macdevlb3, LV_OBJ_FLAG_HIDDEN)) {
    mac = lv_label_get_text(ui_macdevlb3);
    lv_label_set_text(ui_deviceconfigmac, mac);
    lv_disp_load_scr(ui_Screen4);
  }
}

void adddeviceslot4(lv_event_t *e)
{
  (void)e;

  if (!lv_obj_has_flag(ui_macdevlb4, LV_OBJ_FLAG_HIDDEN)) {
    mac = lv_label_get_text(ui_macdevlb1);
    lv_label_set_text(ui_deviceconfigmac, mac);
    lv_disp_load_scr(ui_Screen4);
  }
}

void adddeviceslot5(lv_event_t *e)
{
  (void)e;

  if (!lv_obj_has_flag(ui_macdevlb5, LV_OBJ_FLAG_HIDDEN)) {
    mac = lv_label_get_text(ui_macdevlb5);
    lv_label_set_text(ui_deviceconfigmac, mac);
    lv_disp_load_scr(ui_Screen4);
  }
}

void removeslot0cb(lv_event_t *e)
{
  (void)e;

  remove_completed = false;
  remove_slot = 0;
}

void removeslot1cb(lv_event_t *e)
{
  (void)e;

  remove_completed = false;
  remove_slot = 1;
}

void removeslot2cb(lv_event_t *e)
{
  (void)e;

  remove_completed = false;
  remove_slot = 2;
}

void removeslot3cb(lv_event_t *e)
{
  (void)e;

  remove_completed = false;
  remove_slot = 3;
}

void removeslot4cb(lv_event_t *e)
{
  (void)e;

  remove_completed = false;
  remove_slot = 4;
}

void removeslot5cb(lv_event_t *e)
{
  (void)e;

  remove_completed = false;
  remove_slot = 5;
}

void registercompletecb(lv_event_t *e)
{
  (void)e;

  register_completed = false;
}

void removecompletecb(lv_event_t *e)
{
  (void)e;

  lv_obj_add_flag(ui_removeicon0, LV_OBJ_FLAG_HIDDEN);
  lv_obj_add_flag(ui_removeicon1, LV_OBJ_FLAG_HIDDEN);
  lv_obj_add_flag(ui_removeicon2, LV_OBJ_FLAG_HIDDEN);
  lv_obj_add_flag(ui_removeicon3, LV_OBJ_FLAG_HIDDEN);
  lv_obj_add_flag(ui_removeicon4, LV_OBJ_FLAG_HIDDEN);
  lv_obj_add_flag(ui_removeicon5, LV_OBJ_FLAG_HIDDEN);
  lv_obj_add_flag(ui_tickpn0, LV_OBJ_FLAG_HIDDEN);
  lv_obj_add_flag(ui_settingpn, LV_OBJ_FLAG_CLICKABLE);
  lv_obj_set_x(ui_settingpn, 0);
  lv_obj_set_y(ui_settingpn, 219);
  remove_completed = true;
  remove_slot = 0xFF;
}
