/**************************************************************************//**
 * @file hrm_app.c
 * @brief BLE HRM/SpO2 demo using Maxm86161 sensor
 * @version 1.0.0
*******************************************************************************
* # License
* <b>Copyright 2020 Silicon Laboratories Inc. www.silabs.com</b>
*******************************************************************************
*
* SPDX-License-Identifier: Zlib
*
* The licensor of this software is Silicon Laboratories Inc.
*
* This software is provided \'as-is\', without any express or implied
* warranty. In no event will the authors be held liable for any damages
* arising from the use of this software.
*
* Permission is granted to anyone to use this software for any purpose,
* including commercial applications, and to alter it and redistribute it
* freely, subject to the following restrictions:
*
* 1. The origin of this software must not be misrepresented; you must not
*    claim that you wrote the original software. If you use this software
*    in a product, an acknowledgment in the product documentation would be
*    appreciated but is not required.
* 2. Altered source versions must be plainly marked as such, and must not be
*    misrepresented as being the original software.
* 3. This notice may not be removed or altered from any source distribution.
*
*******************************************************************************
* # Experimental Quality
* This code has not been formally tested and is provided as-is. It is not
* suitable for production environments. In addition, this code will not be
* maintained and there may be no bug maintenance planned for these resources.
* Silicon Labs may update projects from time to time.
******************************************************************************/
#include <hrm_helper.h>
#include <maxm86161_hrm_config.h>
#include <maxm86161_hrm_spo2.h>
#include "em_gpio.h"
#include "em_cmu.h"
#include "em_emu.h"
#include "sl_i2cspm.h"
#include "sl_bt_api.h"
#include "sl_simple_button_instances.h"
#include "sl_sleeptimer.h"
#include "hrm_app.h"
#include "app_timer.h"
#include <glib.h>

/**************************************************************************//**
 * Local defines
 *****************************************************************************/

/**************************************************************************//**
 * Global variables
 *****************************************************************************/
/** Sensor handle for the maxm86161 hrm algorithm */
 maxm_hrm_handle_t *hrmHandle;

 /** Data Storage memory bock required by the maxm86161 hrm algorithm */
 mamx86161_hrm_data_storage_t hrm_data_storage;
 maxm86161_spo2_data_storage_t spo2_data;
 maxm86161_data_storage_t data_storage;

/** Heart Rate result from the si117xhrm algorithm */
static int16_t heart_rate;

/** SpO2 result from the si117xhrm algorithm */
static int16_t spo2;

static int32_t hrm_status = 0;

static bool update_display = false;
static bool hrm_contac_status = false;

mamx86161_hrm_data_t hrm_data;

/** Flag used to indicate HRM/SpO2 state */
static volatile hrm_spo2_state_t hrm_spo2_state = HRM_STATE_IDLE;

static glib_context_t glib_context;

/* This array is generated by LCDAssistant Tool. A image with bitmap format can
 * use this tool to convert to code.
 * To draw an image or custom bitmaps on the oled, the glib_draw_bmp()
 * function can be used.
 * */
const uint8_t silicon_labs_logo[] = {
  0xFF, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
  0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x81, 0x81, 0x81, 0x81, 0x81, 0x01, 0x41,
  0x01, 0x01, 0x01, 0x01, 0x01, 0x81, 0x81, 0x81, 0x81, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
  0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x81, 0x81, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0xFF,
  0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0xC0, 0xE0, 0xE0, 0xF0, 0xF0, 0xF8, 0xF8, 0x3C,
  0x1C, 0x0C, 0x06, 0x06, 0x02, 0x02, 0x03, 0x01, 0x01, 0x61, 0xF0, 0xF8, 0xFC, 0xFC, 0x7E, 0x7E,
  0x7F, 0x3F, 0x3F, 0x3F, 0x3F, 0x3F, 0x3F, 0x3F, 0x3F, 0x3F, 0x3F, 0x3F, 0x3F, 0x3F, 0x7E, 0x76,
  0x60, 0xE0, 0xE0, 0xE0, 0xF0, 0xF0, 0xF8, 0xFD, 0xFF, 0xFF, 0xFE, 0xFC, 0x78, 0x00, 0x00, 0xFF,
  0xFF, 0x00, 0x00, 0x00, 0x3C, 0x7E, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x7F, 0x3F, 0x1F, 0x1F, 0x0E,
  0x0C, 0x1C, 0x1C, 0xFC, 0xF8, 0xF8, 0xF8, 0xF8, 0xF8, 0xF8, 0xF8, 0xF8, 0xF9, 0xF9, 0xF9, 0xF9,
  0xF9, 0xF9, 0xF9, 0xFD, 0xFF, 0x7F, 0x7E, 0x3E, 0x1C, 0x00, 0x00, 0x00, 0x00, 0x80, 0x80, 0x40,
  0x40, 0x60, 0x30, 0x39, 0x1F, 0x1F, 0x0F, 0x0F, 0x07, 0x03, 0x01, 0x00, 0x00, 0x00, 0x00, 0xFF,
  0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x03, 0x03, 0x03, 0x06, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
  0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF,
  0xFF, 0x00, 0xCC, 0x12, 0x12, 0x12, 0xE4, 0x00, 0xFE, 0x00, 0xFE, 0x00, 0x00, 0x00, 0x00, 0xFE,
  0x00, 0x78, 0x84, 0x02, 0x02, 0x02, 0xCC, 0x00, 0x78, 0x84, 0x02, 0x02, 0x84, 0x78, 0x00, 0xFE,
  0x04, 0x18, 0x60, 0x80, 0xFE, 0x00, 0x00, 0x00, 0xFE, 0x00, 0x00, 0x00, 0x00, 0x80, 0x7C, 0x42,
  0x7C, 0x80, 0x00, 0xFE, 0x12, 0x12, 0x12, 0xEC, 0x00, 0xCC, 0x12, 0x12, 0x12, 0xE4, 0x00, 0xFF,
  0xFF, 0x80, 0x80, 0x81, 0x81, 0x81, 0x80, 0x80, 0x81, 0x80, 0x81, 0x81, 0x81, 0x81, 0x80, 0x81,
  0x80, 0x80, 0x80, 0x81, 0x81, 0x81, 0x80, 0x80, 0x80, 0x80, 0x81, 0x81, 0x80, 0x80, 0x80, 0x81,
  0x80, 0x80, 0x80, 0x80, 0x81, 0x80, 0x80, 0x80, 0x81, 0x81, 0x81, 0x81, 0x80, 0x81, 0x80, 0x80,
  0x80, 0x81, 0x80, 0x81, 0x81, 0x81, 0x81, 0x80, 0x80, 0x80, 0x81, 0x81, 0x81, 0x80, 0x80, 0xFF
};

const uint8_t hrm_background [] = {
  0xFF, 0x01, 0x01, 0x01, 0x01, 0x81, 0xC1, 0xC1, 0xC1, 0x81, 0x01, 0x01, 0x81, 0xC1, 0xC1, 0xC1,
  0x81, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
  0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
  0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x81, 0x01, 0x01, 0x01, 0x01, 0x01, 0xFF,
  0xFF, 0x00, 0x00, 0x1E, 0x3F, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
  0xFF, 0x3F, 0x1E, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xEF, 0xAA, 0xEE, 0x00, 0x00, 0x00, 0xFF,
  0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x03, 0x07, 0x0F, 0x1F, 0x1F, 0x0F, 0x07, 0x03, 0x01,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3B, 0x08, 0x38, 0x08, 0x38, 0x00, 0xFF,
  0xFF, 0x00, 0x00, 0x00, 0x00, 0x70, 0x78, 0xC8, 0xC8, 0x98, 0x90, 0x00, 0xF8, 0xF8, 0x88, 0x88,
  0xF8, 0x70, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF,
  0xFF, 0x00, 0x00, 0x00, 0x00, 0x82, 0xC6, 0x64, 0x24, 0x67, 0xC3, 0x80, 0x07, 0x47, 0x60, 0x20,
  0xE0, 0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x38, 0x28, 0xB8, 0x40, 0x20, 0x10, 0x00, 0xFF,
  0xFF, 0x80, 0x80, 0x80, 0x80, 0x87, 0x8F, 0x98, 0x90, 0x98, 0x8F, 0x87, 0x80, 0x98, 0x9C, 0x96,
  0x93, 0x91, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80,
  0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80,
  0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x82, 0x81, 0x80, 0x87, 0x85, 0x87, 0x80, 0xFF
};

/**************************************************************************//**
 * Local prototypes
 *****************************************************************************/
static void hrm_gpio_setup(void);
static void oled_app_init(void);
static void update_digit(glib_display_t *digit, uint16_t data);

/**************************************************************************//**
 * @brief Initialize the HRM application.
 *****************************************************************************/
void hrm_init_app(void)
{
  int32_t err;

  /* Initialize the oled. */
  oled_app_init();

  /* Initialize other peripherals and drivers */
  hrm_gpio_setup();
  // Initialize hrm
  data_storage.spo2 = &spo2_data;
  data_storage.hrm = &hrm_data_storage;
  err = maxm86161_hrm_initialize(&data_storage, &hrmHandle);
  maxm86161_hrm_configure(hrmHandle, NULL, true);

  // if a max86161 is not present on the I2C bus, then shows an error on OLED
  if (err == MAXM86161_HRM_ERROR_INVALID_PART_ID) {
    /* Use Narrow font */
    glib_set_font(&glib_context, (glib_font_t *) &glib_font_6x8);
    glib_draw_string(&glib_context, "Error:", 0, 2);
    glib_draw_string(&glib_context, "cannot", 8, 12);
    glib_draw_string(&glib_context, "detect", 8, 22);
    glib_draw_string(&glib_context, "MAX86161", 8, 32);
    glib_update_display();
  }
  else {
    /* Use 11x18 font */
    glib_set_font(&glib_context, (glib_font_t *) &glib_font_11x18);
    glib_draw_bmp(&glib_context, silicon_labs_logo);
  }

  sl_sleeptimer_delay_millisecond(3000);
  glib_enable_display(false);
  //Start a software timer 500ms interval for update oled
  sl_bt_system_set_soft_timer(16384, DISPLAY_TIMER, 0);
}

/**************************************************************************//**
* @brief Setup GPIO, enable sensor isolation switch
*****************************************************************************/
static void hrm_gpio_setup(void)
{
  /* Enable GPIO clock */
  CMU_ClockEnable(cmuClock_GPIO, true);

  GPIO_PinModeSet(MAXM86161_EN_GPIO_PORT, MAXM86161_EN_GPIO_PIN, gpioModePushPull, 1);
  // need delay to wait the Maxim ready before we can read and write to register
  sl_sleeptimer_delay_millisecond(5);
}

/**************************************************************************//**
 * Simple Button
 * Button state changed callback
 * @param[in] handle
 *    Button event handle
 *****************************************************************************/
void sl_button_on_change(const sl_button_t *handle)
{
  // Button pressed.
  if (sl_button_get_state(handle) == SL_SIMPLE_BUTTON_PRESSED) {
    if (&sl_button_btn0 == handle) {
      sl_bt_external_signal(BTN0_IRQ_EVENT);
    }

    if (&sl_button_max86161_int == handle) {
      sl_bt_external_signal(MAXM86161_IRQ_EVENT);
    }
  }
}

/**************************************************************************//**
 * @brief Process HRM IRQ events.
 *****************************************************************************/
void hrm_process_event(uint32_t event_flags)
{
  if (event_flags & MAXM86161_IRQ_EVENT) {
    maxm86161_hrm_helper_process_irq();
  }

  if (event_flags & BTN0_IRQ_EVENT) {
    if(hrm_spo2_state == HRM_STATE_IDLE) {
      /* Fill lcd with background color */
      glib_clear(&glib_context);
      glib_enable_display(true);
      glib_draw_background(&glib_context, hrm_background,
                           sizeof(hrm_background));
      glib_update_display();

      hrm_spo2_state = HRM_STATE_ACQUIRING;
      maxm86161_hrm_run(hrmHandle);
    }
    else {
      hrm_spo2_state = HRM_STATE_IDLE;
      maxm86161_hrm_pause();
      glib_enable_display(false);
    }
  }
}

/**************************************************************************//**
 * @brief HRM process main loop.
 *****************************************************************************/
void hrm_loop(void)
{
  int16_t num_samples_processed;
  int32_t err;

  err = maxm86161_hrm_process(hrmHandle, &heart_rate, &spo2, 1,
                              &num_samples_processed, &hrm_status, &hrm_data);

  switch (hrm_spo2_state) {
    case HRM_STATE_IDLE:
      update_display = false;
      break;
    case HRM_STATE_ACQUIRING:
    case HRM_STATE_ACTIVE:
      if ((err == MAXM86161_HRM_SUCCESS)
          && (hrm_status & MAXM86161_HRM_STATUS_FRAME_PROCESSED)) {
        hrm_status &= ~MAXM86161_HRM_STATUS_FRAME_PROCESSED;

#if (UART_DEBUG & HRM_LEVEL)
        hrm_helper_output_debug_message(heart_rate, spo2);
#endif

        update_display = true;
        hrm_spo2_state = HRM_STATE_ACTIVE;
      }
#ifdef PROXIMITY
    else if ((hrm_status & MAXM86161_HRM_STATUS_FINGER_OFF)
        || (hrm_status & MAXM86161_HRM_STATUS_SPO2_FINGER_OFF)
        || (hrm_status & MAXM86161_HRM_STATUS_ZERO_CROSSING_INVALID)
        || (maxm86161_get_prox_mode())) {
#else
    else if ((hrm_status & MAXM86161_HRM_STATUS_FINGER_OFF)
        || (hrm_status & MAXM86161_HRM_STATUS_SPO2_FINGER_OFF)
        || (hrm_status & MAXM86161_HRM_STATUS_ZERO_CROSSING_INVALID)) {
#endif
      heart_rate = 0;
      spo2 = 0;
      update_display = true;
      hrm_spo2_state = HRM_STATE_ACQUIRING;
    }
    break;

    default:
      break;
  }
}

/**************************************************************************//**
 * @brief This function returns the current heart rate.
 *****************************************************************************/
int16_t hrm_get_heart_rate(void)
{
  return heart_rate;
}

/**************************************************************************//**
 * @brief This function returns the current finger contact status.
 *****************************************************************************/
bool hrm_get_status(void)
{
  hrm_contac_status = (hrm_spo2_state == HRM_STATE_ACTIVE);
  return hrm_contac_status;
}

/**************************************************************************//**
 * @brief This function returns the SpO2.
 *****************************************************************************/
int16_t hrm_get_spo2(void)
{
  return spo2;
}

/**************************************************************************//**
 * Initialize OLED display.
 *****************************************************************************/
static void oled_app_init(void)
{
  /* Initialize the display */
  glib_init();

  glib_context.backgroundColor = Black;
  glib_context.foregroundColor = White;

  /* Fill lcd with background color */
  glib_clear(&glib_context);
}

/**************************************************************************//**
 * @brief Update the HRM/SpO2 Demo LCD Display
 *****************************************************************************/
void hrm_update_display(void)
{
  glib_display_t hrm_string;
  uint8_t i;

  /*  Update the Display  */
  if (update_display) {
    update_display = false;

    update_digit(&hrm_string, heart_rate);
    for (i = 0; i< 3; i++)
      glib_draw_char(&glib_context, hrm_string.index[i], 20 + 11*i, 6);

    update_digit(&hrm_string, spo2);
    for (i = 0; i< 3; i++)
      glib_draw_char(&glib_context, hrm_string.index[i], 20 + 11*i, 27);

    glib_update_display();
  }
}

/**************************************************************************//**
 * @brief Update the digits to prepare show on LCD display
 *****************************************************************************/
static void update_digit(glib_display_t *digit, uint16_t data)
{
  digit->index[0] = (data % 1000) / 100 + 0x30;
  digit->index[1] = (data % 100) / 10 + 0x30;
  digit->index[2] = data % 10 + 0x30;

  if (digit->index[0] == '0') {
    digit->index[0] = ' ';
    if (digit->index[1] == '0') {
      digit->index[1] = ' ';
    }
  }
}
