#include <stddef.h>
#include <stdint.h>
#include "app.h"
#ifdef USE_CUSTOM_CERTIFICATES
const uint8_t custom_root_certificate[]=
    "-----BEGIN CERTIFICATE-----\n"
    "MIIBkjCCATigAwIBAgIUIo5fK6UqTeJAbWDfZtLMqJcBfjowCgYIKoZIzj0EAwIw\n"
    "PTELMAkGA1UEBhMCVVMxFTATBgNVBAoMDFNpbGljb24gTGFiczEXMBUGA1UEAwwO\n"
    "Qmx1ZXRvb3RoU3RldmUwHhcNMjEwOTAxMTkyNDQ1WhcNMjExMDAxMTkyNDQ1WjA9\n"
    "MQswCQYDVQQGEwJVUzEVMBMGA1UECgwMU2lsaWNvbiBMYWJzMRcwFQYDVQQDDA5C\n"
    "bHVldG9vdGhTdGV2ZTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABA9rQjkY+wUN\n"
    "wxlcCjti9OwAZhURXn/FA8j2Q3zMTCdCahTOGCj6U4eQuKJOWY/mJXjiRPMnV7np\n"
    "nTPGzsn97TOjFjAUMBIGA1UdEwEB/wQIMAYBAf8CAQIwCgYIKoZIzj0EAwIDSAAw\n"
    "RQIgby2KxiOE7qejg7B7TmqPLfk41dz2j3vnh1ecqhti3PMCIQC2BB/NzgNNgDxo\n"
    "TL1Xx0hJyaZPZfipyfJ5UhxPdnVX3g==\n"
    "-----END CERTIFICATE-----";
const uint8_t custom_factory_certificate[] =
    "-----BEGIN CERTIFICATE-----\n"
    "MIIBiDCCAS6gAwIBAgIUeQPXEl8FgTM0YYMzZEN+cMFij6cwCgYIKoZIzj0EAwIw\n"
    "PTELMAkGA1UEBhMCVVMxFTATBgNVBAoMDFNpbGljb24gTGFiczEXMBUGA1UEAwwO\n"
    "Qmx1ZXRvb3RoU3RldmUwHhcNMjEwOTAxMTk1NDAxWhcNMjExMDAxMTk1NDAxWjAz\n"
    "MQswCQYDVQQGEwJDTjEVMBMGA1UECgwMU2lsaWNvbiBMYWJzMQ0wCwYDVQQDDARO\n"
    "QU1FMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAELSCm0fxzrAtQL63e43xdmr1y\n"
    "NbBxLFagKko08IYFlVz1GMqN98wQwqQ1hEfT0J6jYQ7q3TTX4/PaRJlPJ0dMAKMW\n"
    "MBQwEgYDVR0TAQH/BAgwBgEB/wIBATAKBggqhkjOPQQDAgNIADBFAiEAyAM8egKg\n"
    "K8vpvGXicSKuX41uVjFWB0/uH7m27/wpGqoCIBqaZi/Kdjeu3mkvINNWy8zOfyjE\n"
    "16mvXwozODFAPkqDMAgwBgYEVR0lAA==\n"
    "-----END CERTIFICATE-----\n";

/*need secure boot to guarantee tamper resistance on these certs*/
const uint8_t custom_batch_certificate[]=
    "-----BEGIN CERTIFICATE-----\n"
    "MIIBiTCCAS6gAwIBAgIUerRzaEA11XvXWfagPEDFVju3OlYwCgYIKoZIzj0EAwIw\n"
    "MzELMAkGA1UEBhMCQ04xFTATBgNVBAoMDFNpbGljb24gTGFiczENMAsGA1UEAwwE\n"
    "TkFNRTAeFw0yMTA5MDExOTU0MTlaFw0yMTEwMDExOTU0MTlaMD0xCzAJBgNVBAYT\n"
    "AlVTMRUwEwYDVQQKDAxTaWxpY29uIExhYnMxFzAVBgNVBAMMDkJsdWV0b290aFN0\n"
    "ZXZlMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE0tXRkwtnmlkx4wASWi2ABo9+\n"
    "9CCJ+j9eBLHZd46ofddKL1QEnqGsbtVSiZ/bp5gqZimdDCkuxglBmmXnnzZ3BaMW\n"
    "MBQwEgYDVR0TAQH/BAgwBgEB/wIBADAKBggqhkjOPQQDAgNJADBGAiEAjQhTZ0Oe\n"
    "IXGrBW9OhubE1Pqy1Q5aHbAcpUZrJv/IhG8CIQCJTstu2vpLtoIiwF2T+dJhdihS\n"
    "y0BSi00ebBtTrH4vQTAIMAYGBFUdJQA=\n"
    "-----END CERTIFICATE-----\n";
const uint8_t custom_device_certificate[]=
    "-----BEGIN CERTIFICATE-----\n"
    "MIIBgjCCASmgAwIBAgIUbMGMEzHO+QLIPjOPMnASYOP7I+4wCgYIKoZIzj0EAwIw\n"
    "PTELMAkGA1UEBhMCVVMxFTATBgNVBAoMDFNpbGljb24gTGFiczEXMBUGA1UEAwwO\n"
    "Qmx1ZXRvb3RoU3RldmUwHhcNMjEwOTAxMjE1OTAyWhcNMjExMDAxMjE1OTAyWjA0\n"
    "MQswCQYDVQQGEwJVUzELMAkGA1UECgwCU0wxGDAWBgNVBAMMD0lPVEFwcHNTZWN1\n"
    "cml0eTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABOqlzT0OwZxlfFumEyoZqesj\n"
    "kzFI5PzkuVvy2ZApP7l9nIGoUGfc26thkaNkNvjSs7zd2mcCemzG6oqfPWascq6j\n"
    "EDAOMAwGA1UdEwEB/wQCMAAwCgYIKoZIzj0EAwIDRwAwRAIgEw5ukV7E8Oz7PDc1\n"
    "PsgjqkIDmZvc4DLy6l81tAMXthcCIGrwcOUqZBgrVQxWoqH+f25uSMyMNK633fHJ\n"
    "120148CF\n"
    "-----END CERTIFICATE-----\n";



#define DEVICE_CERT  custom_device_certificate
#define BATCH_CERT   custom_batch_certificate
#define FACTORY_CERT custom_factory_certificate
#define ROOT_CERT    custom_root_certificate



#else
static const uint8_t factory[] =
  "-----BEGIN CERTIFICATE-----\n"
  "MIICEjCCAbmgAwIBAgIIJNx7QAwynAowCgYIKoZIzj0EAwIwQjEXMBUGA1UEAwwO\n"
  "RGV2aWNlIFJvb3QgQ0ExGjAYBgNVBAoMEVNpbGljb24gTGFicyBJbmMuMQswCQYD\n"
  "VQQGEwJVUzAgFw0xODEwMTAxNzMzMDBaGA8yMTE4MDkxNjE3MzIwMFowOzEQMA4G\n"
  "A1UEAwwHRmFjdG9yeTEaMBgGA1UECgwRU2lsaWNvbiBMYWJzIEluYy4xCzAJBgNV\n"
  "BAYTAlVTMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEatHnJa9nUyTyJtuY6xgE\n"
  "msybdzjhCbmKo3qMzAt/GQ4/TKIXkCwhw1Ni6kmQzh4qrINPYWP8vnG6tPJUyzUp\n"
  "VKOBnTCBmjASBgNVHRMBAf8ECDAGAQH/AgEBMB8GA1UdIwQYMBaAFBCLCj7NdHWU\n"
  "9EyEIs2OIqSrMaVCMDQGA1UdHwQtMCswKaAnoCWGI2h0dHA6Ly9jYS5zaWxhYnMu\n"
  "Y29tL2RldmljZXJvb3QuY3JsMB0GA1UdDgQWBBRDYoRJaG86aXx20B/lHSr513PR\n"
  "FjAOBgNVHQ8BAf8EBAMCAYYwCgYIKoZIzj0EAwIDRwAwRAIgY34nvceLA1h3xYgt\n"
  "mdzguHn7yNYlJQXDp7F8iNLRTBkCIAwkPej1R90Hw2o48eNvOmJG+QeLAUdVlIGY\n"
  "07PRgSaC\n"
  "-----END CERTIFICATE-----\n";

/// Root certificate
static const uint8_t root[] =
  "-----BEGIN CERTIFICATE-----\n"
  "MIICGTCCAcCgAwIBAgIIEuaipZyqJ/kwCgYIKoZIzj0EAwIwQjEXMBUGA1UEAwwO\n"
  "RGV2aWNlIFJvb3QgQ0ExGjAYBgNVBAoMEVNpbGljb24gTGFicyBJbmMuMQswCQYD\n"
  "VQQGEwJVUzAgFw0xODEwMTAxNzMyMDBaGA8yMTE4MDkxNjE3MzIwMFowQjEXMBUG\n"
  "A1UEAwwORGV2aWNlIFJvb3QgQ0ExGjAYBgNVBAoMEVNpbGljb24gTGFicyBJbmMu\n"
  "MQswCQYDVQQGEwJVUzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABNAp5f+cr+v9\n"
  "zxfMQMJjxLxaqdBWe4nTrCwHihHtxYZDYsSBgdzZ3VFUu0xTlP07dWsuCL99abzl\n"
  "Qyqak+tdTS2jgZ0wgZowEgYDVR0TAQH/BAgwBgEB/wIBAjAfBgNVHSMEGDAWgBQQ\n"
  "iwo+zXR1lPRMhCLNjiKkqzGlQjA0BgNVHR8ELTArMCmgJ6AlhiNodHRwOi8vY2Eu\n"
  "c2lsYWJzLmNvbS9kZXZpY2Vyb290LmNybDAdBgNVHQ4EFgQUEIsKPs10dZT0TIQi\n"
  "zY4ipKsxpUIwDgYDVR0PAQH/BAQDAgGGMAoGCCqGSM49BAMCA0cAMEQCIGlwr4G7\n"
  "IkG/9XHHk1WPthnY/yNNIzP9pThZkg2zU88ZAiBkAhsPaMKE7NOwWQIBgxy9nevX\n"
  "c7VKkqNr4UAU5zPbxg==\n"
  "-----END CERTIFICATE-----\n";

#define DEVICE_CERT
#define BATCH_CERT
#define FACTORY_CERT factory
#define ROOT_CERT    root
#endif
//#define FACTORY_CERT factory
//#define ROOT_CERT    root
