#include "app.h"
#include <stdint.h>
/**/

/// Factory certificate
const uint8_t factory[] =
  "-----BEGIN CERTIFICATE-----\n"
  "MIICEjCCAbmgAwIBAgIIJNx7QAwynAowCgYIKoZIzj0EAwIwQjEXMBUGA1UEAwwO\n"
  "RGV2aWNlIFJvb3QgQ0ExGjAYBgNVBAoMEVNpbGljb24gTGFicyBJbmMuMQswCQYD\n"
  "VQQGEwJVUzAgFw0xODEwMTAxNzMzMDBaGA8yMTE4MDkxNjE3MzIwMFowOzEQMA4G\n"
  "A1UEAwwHRmFjdG9yeTEaMBgGA1UECgwRU2lsaWNvbiBMYWJzIEluYy4xCzAJBgNV\n"
  "BAYTAlVTMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEatHnJa9nUyTyJtuY6xgE\n"
  "msybdzjhCbmKo3qMzAt/GQ4/TKIXkCwhw1Ni6kmQzh4qrINPYWP8vnG6tPJUyzUp\n"
  "VKOBnTCBmjASBgNVHRMBAf8ECDAGAQH/AgEBMB8GA1UdIwQYMBaAFBCLCj7NdHWU\n"
  "9EyEIs2OIqSrMaVCMDQGA1UdHwQtMCswKaAnoCWGI2h0dHA6Ly9jYS5zaWxhYnMu\n"
  "Y29tL2RldmljZXJvb3QuY3JsMB0GA1UdDgQWBBRDYoRJaG86aXx20B/lHSr513PR\n"
  "FjAOBgNVHQ8BAf8EBAMCAYYwCgYIKoZIzj0EAwIDRwAwRAIgY34nvceLA1h3xYgt\n"
  "mdzguHn7yNYlJQXDp7F8iNLRTBkCIAwkPej1R90Hw2o48eNvOmJG+QeLAUdVlIGY\n"
  "07PRgSaC\n"
  "-----END CERTIFICATE-----\n";

/// Root certificate
const uint8_t root[] =
  "-----BEGIN CERTIFICATE-----\n"
  "MIICGTCCAcCgAwIBAgIIEuaipZyqJ/kwCgYIKoZIzj0EAwIwQjEXMBUGA1UEAwwO\n"
  "RGV2aWNlIFJvb3QgQ0ExGjAYBgNVBAoMEVNpbGljb24gTGFicyBJbmMuMQswCQYD\n"
  "VQQGEwJVUzAgFw0xODEwMTAxNzMyMDBaGA8yMTE4MDkxNjE3MzIwMFowQjEXMBUG\n"
  "A1UEAwwORGV2aWNlIFJvb3QgQ0ExGjAYBgNVBAoMEVNpbGljb24gTGFicyBJbmMu\n"
  "MQswCQYDVQQGEwJVUzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABNAp5f+cr+v9\n"
  "zxfMQMJjxLxaqdBWe4nTrCwHihHtxYZDYsSBgdzZ3VFUu0xTlP07dWsuCL99abzl\n"
  "Qyqak+tdTS2jgZ0wgZowEgYDVR0TAQH/BAgwBgEB/wIBAjAfBgNVHSMEGDAWgBQQ\n"
  "iwo+zXR1lPRMhCLNjiKkqzGlQjA0BgNVHR8ELTArMCmgJ6AlhiNodHRwOi8vY2Eu\n"
  "c2lsYWJzLmNvbS9kZXZpY2Vyb290LmNybDAdBgNVHQ4EFgQUEIsKPs10dZT0TIQi\n"
  "zY4ipKsxpUIwDgYDVR0PAQH/BAQDAgGGMAoGCCqGSM49BAMCA0cAMEQCIGlwr4G7\n"
  "IkG/9XHHk1WPthnY/yNNIzP9pThZkg2zU88ZAiBkAhsPaMKE7NOwWQIBgxy9nevX\n"
  "c7VKkqNr4UAU5zPbxg==\n"
  "-----END CERTIFICATE-----\n";

