// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
  ui_Screen2 = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_bg_color(ui_Screen2,
                            lv_color_hex(0xFFFFFF),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_silabslogoscr2 = lv_img_create(ui_Screen2);
  lv_img_set_src(ui_silabslogoscr2, &ui_img_1228364278);
  lv_obj_set_width(ui_silabslogoscr2, LV_SIZE_CONTENT); /// 83
  lv_obj_set_height(ui_silabslogoscr2, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_x(ui_silabslogoscr2, -115);
  lv_obj_set_y(ui_silabslogoscr2, -212);
  lv_obj_set_align(ui_silabslogoscr2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_silabslogoscr2, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_clear_flag(ui_silabslogoscr2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  ui_removedevpn = lv_obj_create(ui_Screen2);
  lv_obj_set_width(ui_removedevpn, 250);
  lv_obj_set_height(ui_removedevpn, 40);
  lv_obj_set_x(ui_removedevpn, 1);
  lv_obj_set_y(ui_removedevpn, -41);
  lv_obj_set_align(ui_removedevpn, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_removedevpn, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_bg_color(ui_removedevpn,
                            lv_color_hex(0x0278F0),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_removedevpn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_removedevpn,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_removedevlb = lv_label_create(ui_removedevpn);
  lv_obj_set_width(ui_removedevlb, LV_SIZE_CONTENT); /// 1
  lv_obj_set_height(ui_removedevlb, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_removedevlb, -4);
  lv_obj_set_y(ui_removedevlb, -1);
  lv_obj_set_align(ui_removedevlb, LV_ALIGN_CENTER);
  lv_label_set_text(ui_removedevlb, "Remove client device");
  lv_obj_set_style_text_color(ui_removedevlb,
                              lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_removedevlb, 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_adddevpn = lv_obj_create(ui_Screen2);
  lv_obj_set_width(ui_adddevpn, 250);
  lv_obj_set_height(ui_adddevpn, 40);
  lv_obj_set_x(ui_adddevpn, 0);
  lv_obj_set_y(ui_adddevpn, 17);
  lv_obj_set_align(ui_adddevpn, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_adddevpn, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_bg_color(ui_adddevpn,
                            lv_color_hex(0x0278F0),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_adddevpn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_adddevpn,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_adddevlb = lv_label_create(ui_adddevpn);
  lv_obj_set_width(ui_adddevlb, LV_SIZE_CONTENT); /// 1
  lv_obj_set_height(ui_adddevlb, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_adddevlb, -4);
  lv_obj_set_y(ui_adddevlb, -1);
  lv_obj_set_align(ui_adddevlb, LV_ALIGN_CENTER);
  lv_label_set_text(ui_adddevlb, "Add new devices");
  lv_obj_set_style_text_color(ui_adddevlb,
                              lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_adddevlb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_exitscr3pn2 = lv_obj_create(ui_Screen2);
  lv_obj_set_width(ui_exitscr3pn2, 58);
  lv_obj_set_height(ui_exitscr3pn2, 35);
  lv_obj_set_x(ui_exitscr3pn2, 6);
  lv_obj_set_y(ui_exitscr3pn2, 219);
  lv_obj_set_align(ui_exitscr3pn2, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_exitscr3pn2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_radius(ui_exitscr3pn2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_exitscr3pn2,
                            lv_color_hex(0xF78C81),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_exitscr3pn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_exitscr3pn2,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_exiticon2 = lv_img_create(ui_exitscr3pn2);
  lv_img_set_src(ui_exiticon2, &ui_img_exit_icon_png);
  lv_obj_set_width(ui_exiticon2, LV_SIZE_CONTENT); /// 128
  lv_obj_set_height(ui_exiticon2, LV_SIZE_CONTENT);  /// 128
  lv_obj_set_align(ui_exiticon2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_exiticon2, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_clear_flag(ui_exiticon2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_exiticon2, 50);

  ui_warningpn = lv_obj_create(ui_Screen2);
  lv_obj_set_width(ui_warningpn, 250);
  lv_obj_set_height(ui_warningpn, 100);
  lv_obj_set_x(ui_warningpn, 0);
  lv_obj_set_y(ui_warningpn, -122);
  lv_obj_set_align(ui_warningpn, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_warningpn, LV_OBJ_FLAG_HIDDEN);   /// Flags
  lv_obj_clear_flag(ui_warningpn, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_bg_color(ui_warningpn,
                            lv_color_hex(0xFAAD45),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_warningpn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_warningpn,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_removewarninglb = lv_label_create(ui_warningpn);
  lv_obj_set_width(ui_removewarninglb, 220);
  lv_obj_set_height(ui_removewarninglb, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_removewarninglb, 2);
  lv_obj_set_y(ui_removewarninglb, 21);
  lv_obj_set_align(ui_removewarninglb, LV_ALIGN_CENTER);
  lv_label_set_text(ui_removewarninglb, "");
  lv_obj_set_style_text_color(ui_removewarninglb,
                              lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_removewarninglb,
                            255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_removewarninglb,
                              LV_TEXT_ALIGN_CENTER,
                              LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_warningicon = lv_img_create(ui_warningpn);
  lv_img_set_src(ui_warningicon, &ui_img_warning_icon_png);
  lv_obj_set_width(ui_warningicon, LV_SIZE_CONTENT); /// 110
  lv_obj_set_height(ui_warningicon, LV_SIZE_CONTENT);  /// 110
  lv_obj_set_x(ui_warningicon, -2);
  lv_obj_set_y(ui_warningicon, -19);
  lv_obj_set_align(ui_warningicon, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_warningicon, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_clear_flag(ui_warningicon, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_warningicon, 100);

  lv_obj_add_event_cb(ui_removedevpn, ui_event_removedevpn, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_adddevpn, ui_event_adddevpn, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_exitscr3pn2, ui_event_exitscr3pn2, LV_EVENT_ALL, NULL);
}
