// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
  ui_Screen1 = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_bg_color(ui_Screen1,
                            lv_color_hex(0xFFFFFF),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_headerpn = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_headerpn, 320);
  lv_obj_set_height(ui_headerpn, 70);
  lv_obj_set_x(ui_headerpn, 1);
  lv_obj_set_y(ui_headerpn, -203);
  lv_obj_set_align(ui_headerpn, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_headerpn, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_radius(ui_headerpn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_headerpn,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_border_side(ui_headerpn,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

  ui_silabslogoscr1 = lv_img_create(ui_headerpn);
  lv_img_set_src(ui_silabslogoscr1, &ui_img_1228364278);
  lv_obj_set_width(ui_silabslogoscr1, LV_SIZE_CONTENT); /// 83
  lv_obj_set_height(ui_silabslogoscr1, LV_SIZE_CONTENT);  /// 48
  lv_obj_set_x(ui_silabslogoscr1, -113);
  lv_obj_set_y(ui_silabslogoscr1, -13);
  lv_obj_set_align(ui_silabslogoscr1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_silabslogoscr1, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_clear_flag(ui_silabslogoscr1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  ui_prjname0 = lv_label_create(ui_headerpn);
  lv_obj_set_width(ui_prjname0, LV_SIZE_CONTENT); /// 1
  lv_obj_set_height(ui_prjname0, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_prjname0, 42);
  lv_obj_set_y(ui_prjname0, -12);
  lv_obj_set_align(ui_prjname0, LV_ALIGN_CENTER);
  lv_label_set_text(ui_prjname0, "BTHome v2 - Server Example");
  lv_obj_set_style_text_font(ui_prjname0,
                             &lv_font_montserrat_14,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_inforpanel0 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_inforpanel0, 310);
  lv_obj_set_height(ui_inforpanel0, 60);
  lv_obj_set_x(ui_inforpanel0, 0);
  lv_obj_set_y(ui_inforpanel0, -155);
  lv_obj_set_align(ui_inforpanel0, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_inforpanel0, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_add_flag(ui_inforpanel0, LV_OBJ_FLAG_HIDDEN);
  lv_obj_add_flag(ui_inforpanel0, LV_OBJ_FLAG_HIDDEN);
  lv_obj_set_style_bg_color(ui_inforpanel0,
                            lv_color_hex(0x7FB2F0),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_inforpanel0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_inforpanel0,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_border_side(ui_inforpanel0,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

  ui_deviceinforlb0 = lv_label_create(ui_inforpanel0);
  lv_obj_set_width(ui_deviceinforlb0, 69);
  lv_obj_set_height(ui_deviceinforlb0, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_deviceinforlb0, 97);
  lv_obj_set_y(ui_deviceinforlb0, -3);
  lv_obj_set_align(ui_deviceinforlb0, LV_ALIGN_CENTER);
  lv_label_set_text(ui_deviceinforlb0, "");
  lv_obj_set_style_text_color(ui_deviceinforlb0,
                              lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_deviceinforlb0,
                            255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_deviceinforlb0,
                              LV_TEXT_ALIGN_CENTER,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_deviceinforlb0,
                             &lv_font_montserrat_20,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_maclb0 = lv_label_create(ui_inforpanel0);
  lv_obj_set_width(ui_maclb0, 160);
  lv_obj_set_height(ui_maclb0, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_maclb0, -70);
  lv_obj_set_y(ui_maclb0, -13);
  lv_obj_set_align(ui_maclb0, LV_ALIGN_CENTER);
  lv_label_set_text(ui_maclb0, "");
  lv_obj_set_style_text_color(ui_maclb0,
                              lv_color_hex(0x00FA28),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_maclb0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_maclb0,
                             &lv_font_montserrat_16,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_historylb0 = lv_label_create(ui_inforpanel0);
  lv_obj_set_width(ui_historylb0, 90);
  lv_obj_set_height(ui_historylb0, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_historylb0, 103);
  lv_obj_set_y(ui_historylb0, 19);
  lv_obj_set_align(ui_historylb0, LV_ALIGN_CENTER);
  lv_label_set_text(ui_historylb0, "");
  lv_obj_set_style_text_color(ui_historylb0,
                              lv_color_hex(0xF64C07),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_historylb0, 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_historylb0,
                              LV_TEXT_ALIGN_LEFT,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_historylb0,
                             &lv_font_montserrat_10,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_deviceiconpn0 = lv_obj_create(ui_inforpanel0);
  lv_obj_set_width(ui_deviceiconpn0, 45);
  lv_obj_set_height(ui_deviceiconpn0, 50);
  lv_obj_set_x(ui_deviceiconpn0, 28);
  lv_obj_set_y(ui_deviceiconpn0, -1);
  lv_obj_set_align(ui_deviceiconpn0, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_deviceiconpn0, LV_OBJ_FLAG_HIDDEN);   /// Flags
  lv_obj_clear_flag(ui_deviceiconpn0, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_bg_color(ui_deviceiconpn0,
                            lv_color_hex(0x7FB2F0),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_deviceiconpn0, 255,
                          LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_deviceiconpn0,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_lightofficon0 = lv_img_create(ui_deviceiconpn0);
  lv_img_set_src(ui_lightofficon0, &ui_img_light_off_icon_png);
  lv_obj_set_width(ui_lightofficon0, LV_SIZE_CONTENT); /// 63
  lv_obj_set_height(ui_lightofficon0, LV_SIZE_CONTENT);  /// 80
  lv_obj_set_x(ui_lightofficon0, 1);
  lv_obj_set_y(ui_lightofficon0, 0);
  lv_obj_set_align(ui_lightofficon0, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_lightofficon0,
                  LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_lightofficon0, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_lightofficon0, 150);

  ui_tempicon0 = lv_img_create(ui_deviceiconpn0);
  lv_img_set_src(ui_tempicon0, &ui_img_temperature_icon_png);
  lv_obj_set_width(ui_tempicon0, LV_SIZE_CONTENT); /// 128
  lv_obj_set_height(ui_tempicon0, LV_SIZE_CONTENT);  /// 129
  lv_obj_set_x(ui_tempicon0, -1);
  lv_obj_set_y(ui_tempicon0, -1);
  lv_obj_set_align(ui_tempicon0, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_tempicon0, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_tempicon0, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_tempicon0, 80);

  ui_butofficon0 = lv_img_create(ui_deviceiconpn0);
  lv_img_set_src(ui_butofficon0, &ui_img_button_off_ic_1_png);
  lv_obj_set_width(ui_butofficon0, LV_SIZE_CONTENT); /// 42
  lv_obj_set_height(ui_butofficon0, LV_SIZE_CONTENT);  /// 42
  lv_obj_set_align(ui_butofficon0, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_butofficon0, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_butofficon0, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  ui_butonicon0 = lv_img_create(ui_deviceiconpn0);
  lv_img_set_src(ui_butonicon0, &ui_img_button_on_ic_1_png);
  lv_obj_set_width(ui_butonicon0, LV_SIZE_CONTENT); /// 43
  lv_obj_set_height(ui_butonicon0, LV_SIZE_CONTENT);  /// 40
  lv_obj_set_x(ui_butonicon0, -1);
  lv_obj_set_y(ui_butonicon0, 1);
  lv_obj_set_align(ui_butonicon0, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_butonicon0, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_butonicon0, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  ui_lightonicon0 = lv_img_create(ui_deviceiconpn0);
  lv_img_set_src(ui_lightonicon0, &ui_img_light_on_icon_1_png);
  lv_obj_set_width(ui_lightonicon0, LV_SIZE_CONTENT); /// 53
  lv_obj_set_height(ui_lightonicon0, LV_SIZE_CONTENT);  /// 76
  lv_obj_set_x(ui_lightonicon0, 1);
  lv_obj_set_y(ui_lightonicon0, -1);
  lv_obj_set_align(ui_lightonicon0, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_lightonicon0,
                  LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_lightonicon0, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_lightonicon0, 150);

  ui_devicenamelb0 = lv_label_create(ui_inforpanel0);
  lv_obj_set_width(ui_devicenamelb0, 160);
  lv_obj_set_height(ui_devicenamelb0, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_devicenamelb0, -70);
  lv_obj_set_y(ui_devicenamelb0, 10);
  lv_obj_set_align(ui_devicenamelb0, LV_ALIGN_CENTER);
  lv_label_set_text(ui_devicenamelb0, "");
  lv_obj_set_style_text_color(ui_devicenamelb0,
                              lv_color_hex(0xFBE008),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_devicenamelb0,
                            255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_devicenamelb0,
                             &lv_font_montserrat_16,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_removeicon0 = lv_img_create(ui_inforpanel0);
  lv_img_set_src(ui_removeicon0, &ui_img_rm_icon_png);
  lv_obj_set_width(ui_removeicon0, LV_SIZE_CONTENT); /// 118
  lv_obj_set_height(ui_removeicon0, LV_SIZE_CONTENT);  /// 119
  lv_obj_set_x(ui_removeicon0, 142);
  lv_obj_set_y(ui_removeicon0, -18);
  lv_obj_set_align(ui_removeicon0, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_removeicon0,
                  LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE
                  | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_removeicon0, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_removeicon0, 40);

  ui_inforpanel1 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_inforpanel1, 310);
  lv_obj_set_height(ui_inforpanel1, 60);
  lv_obj_set_x(ui_inforpanel1, 0);
  lv_obj_set_y(ui_inforpanel1, -90);
  lv_obj_set_align(ui_inforpanel1, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_inforpanel1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_add_flag(ui_inforpanel1, LV_OBJ_FLAG_HIDDEN);
  lv_obj_set_style_bg_color(ui_inforpanel1,
                            lv_color_hex(0x509BF9),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_inforpanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_inforpanel1,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_border_side(ui_inforpanel1,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

  ui_maclb1 = lv_label_create(ui_inforpanel1);
  lv_obj_set_width(ui_maclb1, 160);
  lv_obj_set_height(ui_maclb1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_maclb1, -70);
  lv_obj_set_y(ui_maclb1, -13);
  lv_obj_set_align(ui_maclb1, LV_ALIGN_CENTER);
  lv_label_set_text(ui_maclb1, "");
  lv_obj_set_style_text_color(ui_maclb1,
                              lv_color_hex(0x00FA28),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_maclb1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_maclb1,
                             &lv_font_montserrat_16,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_devicenamelb1 = lv_label_create(ui_inforpanel1);
  lv_obj_set_width(ui_devicenamelb1, 160);
  lv_obj_set_height(ui_devicenamelb1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_devicenamelb1, -70);
  lv_obj_set_y(ui_devicenamelb1, 10);
  lv_obj_set_align(ui_devicenamelb1, LV_ALIGN_CENTER);
  lv_label_set_text(ui_devicenamelb1, "");
  lv_obj_set_style_text_color(ui_devicenamelb1,
                              lv_color_hex(0xFBE008),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_devicenamelb1,
                            255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_devicenamelb1,
                             &lv_font_montserrat_16,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_removeicon1 = lv_img_create(ui_inforpanel1);
  lv_img_set_src(ui_removeicon1, &ui_img_rm_icon_png);
  lv_obj_set_width(ui_removeicon1, LV_SIZE_CONTENT); /// 118
  lv_obj_set_height(ui_removeicon1, LV_SIZE_CONTENT);  /// 119
  lv_obj_set_x(ui_removeicon1, 142);
  lv_obj_set_y(ui_removeicon1, -18);
  lv_obj_set_align(ui_removeicon1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_removeicon1,
                  LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE
                  | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_removeicon1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_removeicon1, 40);

  ui_deviceiconpn1 = lv_obj_create(ui_inforpanel1);
  lv_obj_set_width(ui_deviceiconpn1, 45);
  lv_obj_set_height(ui_deviceiconpn1, 50);
  lv_obj_set_x(ui_deviceiconpn1, 28);
  lv_obj_set_y(ui_deviceiconpn1, -1);
  lv_obj_set_align(ui_deviceiconpn1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_deviceiconpn1, LV_OBJ_FLAG_HIDDEN);   /// Flags
  lv_obj_clear_flag(ui_deviceiconpn1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_bg_color(ui_deviceiconpn1,
                            lv_color_hex(0x509BF9),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_deviceiconpn1, 255,
                          LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_deviceiconpn1,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_lightofficon1 = lv_img_create(ui_deviceiconpn1);
  lv_img_set_src(ui_lightofficon1, &ui_img_light_off_icon_png);
  lv_obj_set_width(ui_lightofficon1, LV_SIZE_CONTENT); /// 63
  lv_obj_set_height(ui_lightofficon1, LV_SIZE_CONTENT);  /// 80
  lv_obj_set_x(ui_lightofficon1, 1);
  lv_obj_set_y(ui_lightofficon1, 0);
  lv_obj_set_align(ui_lightofficon1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_lightofficon1,
                  LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_lightofficon1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_lightofficon1, 150);

  ui_tempicon1 = lv_img_create(ui_deviceiconpn1);
  lv_img_set_src(ui_tempicon1, &ui_img_temperature_icon_png);
  lv_obj_set_width(ui_tempicon1, LV_SIZE_CONTENT); /// 128
  lv_obj_set_height(ui_tempicon1, LV_SIZE_CONTENT);  /// 129
  lv_obj_set_x(ui_tempicon1, -1);
  lv_obj_set_y(ui_tempicon1, -1);
  lv_obj_set_align(ui_tempicon1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_tempicon1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_tempicon1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_tempicon1, 80);

  ui_butofficon1 = lv_img_create(ui_deviceiconpn1);
  lv_img_set_src(ui_butofficon1, &ui_img_button_off_ic_1_png);
  lv_obj_set_width(ui_butofficon1, LV_SIZE_CONTENT); /// 42
  lv_obj_set_height(ui_butofficon1, LV_SIZE_CONTENT);  /// 42
  lv_obj_set_align(ui_butofficon1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_butofficon1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_butofficon1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  ui_butonicon1 = lv_img_create(ui_deviceiconpn1);
  lv_img_set_src(ui_butonicon1, &ui_img_button_on_ic_1_png);
  lv_obj_set_width(ui_butonicon1, LV_SIZE_CONTENT); /// 43
  lv_obj_set_height(ui_butonicon1, LV_SIZE_CONTENT);  /// 40
  lv_obj_set_x(ui_butonicon1, -1);
  lv_obj_set_y(ui_butonicon1, 1);
  lv_obj_set_align(ui_butonicon1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_butonicon1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_butonicon1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  ui_lightonicon1 = lv_img_create(ui_deviceiconpn1);
  lv_img_set_src(ui_lightonicon1, &ui_img_light_on_icon_1_png);
  lv_obj_set_width(ui_lightonicon1, LV_SIZE_CONTENT); /// 53
  lv_obj_set_height(ui_lightonicon1, LV_SIZE_CONTENT);  /// 76
  lv_obj_set_x(ui_lightonicon1, 1);
  lv_obj_set_y(ui_lightonicon1, -1);
  lv_obj_set_align(ui_lightonicon1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_lightonicon1,
                  LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_lightonicon1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_lightonicon1, 150);

  ui_historylb1 = lv_label_create(ui_inforpanel1);
  lv_obj_set_width(ui_historylb1, 90);
  lv_obj_set_height(ui_historylb1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_historylb1, 103);
  lv_obj_set_y(ui_historylb1, 19);
  lv_obj_set_align(ui_historylb1, LV_ALIGN_CENTER);
  lv_label_set_text(ui_historylb1, "");
  lv_obj_set_style_text_color(ui_historylb1,
                              lv_color_hex(0xF64C07),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_historylb1, 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_historylb1,
                              LV_TEXT_ALIGN_LEFT,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_historylb1,
                             &lv_font_montserrat_10,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_deviceinforlb1 = lv_label_create(ui_inforpanel1);
  lv_obj_set_width(ui_deviceinforlb1, 69);
  lv_obj_set_height(ui_deviceinforlb1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_deviceinforlb1, 97);
  lv_obj_set_y(ui_deviceinforlb1, -3);
  lv_obj_set_align(ui_deviceinforlb1, LV_ALIGN_CENTER);
  lv_label_set_text(ui_deviceinforlb1, "");
  lv_obj_set_style_text_color(ui_deviceinforlb1,
                              lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_deviceinforlb1,
                            255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_deviceinforlb1,
                              LV_TEXT_ALIGN_CENTER,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_deviceinforlb1,
                             &lv_font_montserrat_20,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_inforpanel2 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_inforpanel2, 310);
  lv_obj_set_height(ui_inforpanel2, 60);
  lv_obj_set_x(ui_inforpanel2, 0);
  lv_obj_set_y(ui_inforpanel2, -25);
  lv_obj_set_align(ui_inforpanel2, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_inforpanel2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_add_flag(ui_inforpanel2, LV_OBJ_FLAG_HIDDEN);
  lv_obj_set_style_bg_color(ui_inforpanel2,
                            lv_color_hex(0x0B82FE),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_inforpanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_inforpanel2,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_border_side(ui_inforpanel2,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

  ui_devicenamelb2 = lv_label_create(ui_inforpanel2);
  lv_obj_set_width(ui_devicenamelb2, 160);
  lv_obj_set_height(ui_devicenamelb2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_devicenamelb2, -70);
  lv_obj_set_y(ui_devicenamelb2, 10);
  lv_obj_set_align(ui_devicenamelb2, LV_ALIGN_CENTER);
  lv_label_set_text(ui_devicenamelb2, "");
  lv_obj_set_style_text_color(ui_devicenamelb2,
                              lv_color_hex(0xFBE008),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_devicenamelb2,
                            255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_devicenamelb2,
                             &lv_font_montserrat_16,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_maclb2 = lv_label_create(ui_inforpanel2);
  lv_obj_set_width(ui_maclb2, 160);
  lv_obj_set_height(ui_maclb2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_maclb2, -70);
  lv_obj_set_y(ui_maclb2, -13);
  lv_obj_set_align(ui_maclb2, LV_ALIGN_CENTER);
  lv_label_set_text(ui_maclb2, "");
  lv_obj_set_style_text_color(ui_maclb2,
                              lv_color_hex(0x00FA28),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_maclb2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_maclb2,
                             &lv_font_montserrat_16,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_removeicon2 = lv_img_create(ui_inforpanel2);
  lv_img_set_src(ui_removeicon2, &ui_img_rm_icon_png);
  lv_obj_set_width(ui_removeicon2, LV_SIZE_CONTENT); /// 118
  lv_obj_set_height(ui_removeicon2, LV_SIZE_CONTENT);  /// 119
  lv_obj_set_x(ui_removeicon2, 142);
  lv_obj_set_y(ui_removeicon2, -18);
  lv_obj_set_align(ui_removeicon2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_removeicon2,
                  LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE
                  | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_removeicon2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_removeicon2, 40);

  ui_deviceiconpn2 = lv_obj_create(ui_inforpanel2);
  lv_obj_set_width(ui_deviceiconpn2, 45);
  lv_obj_set_height(ui_deviceiconpn2, 50);
  lv_obj_set_x(ui_deviceiconpn2, 28);
  lv_obj_set_y(ui_deviceiconpn2, -1);
  lv_obj_set_align(ui_deviceiconpn2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_deviceiconpn2, LV_OBJ_FLAG_HIDDEN);   /// Flags
  lv_obj_clear_flag(ui_deviceiconpn2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_bg_color(ui_deviceiconpn2,
                            lv_color_hex(0x0B82FE),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_deviceiconpn2, 255,
                          LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_deviceiconpn2,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_lightofficon2 = lv_img_create(ui_deviceiconpn2);
  lv_img_set_src(ui_lightofficon2, &ui_img_light_off_icon_png);
  lv_obj_set_width(ui_lightofficon2, LV_SIZE_CONTENT); /// 63
  lv_obj_set_height(ui_lightofficon2, LV_SIZE_CONTENT);  /// 80
  lv_obj_set_x(ui_lightofficon2, 1);
  lv_obj_set_y(ui_lightofficon2, 0);
  lv_obj_set_align(ui_lightofficon2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_lightofficon2,
                  LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_lightofficon2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_lightofficon2, 150);

  ui_tempicon2 = lv_img_create(ui_deviceiconpn2);
  lv_img_set_src(ui_tempicon2, &ui_img_temperature_icon_png);
  lv_obj_set_width(ui_tempicon2, LV_SIZE_CONTENT); /// 128
  lv_obj_set_height(ui_tempicon2, LV_SIZE_CONTENT);  /// 129
  lv_obj_set_x(ui_tempicon2, -1);
  lv_obj_set_y(ui_tempicon2, -1);
  lv_obj_set_align(ui_tempicon2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_tempicon2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_tempicon2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_tempicon2, 80);

  ui_butofficon2 = lv_img_create(ui_deviceiconpn2);
  lv_img_set_src(ui_butofficon2, &ui_img_button_off_ic_1_png);
  lv_obj_set_width(ui_butofficon2, LV_SIZE_CONTENT); /// 42
  lv_obj_set_height(ui_butofficon2, LV_SIZE_CONTENT);  /// 42
  lv_obj_set_align(ui_butofficon2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_butofficon2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_butofficon2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  ui_butonicon2 = lv_img_create(ui_deviceiconpn2);
  lv_img_set_src(ui_butonicon2, &ui_img_button_on_ic_1_png);
  lv_obj_set_width(ui_butonicon2, LV_SIZE_CONTENT); /// 43
  lv_obj_set_height(ui_butonicon2, LV_SIZE_CONTENT);  /// 40
  lv_obj_set_x(ui_butonicon2, -1);
  lv_obj_set_y(ui_butonicon2, 1);
  lv_obj_set_align(ui_butonicon2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_butonicon2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_butonicon2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  ui_lightonicon2 = lv_img_create(ui_deviceiconpn2);
  lv_img_set_src(ui_lightonicon2, &ui_img_light_on_icon_1_png);
  lv_obj_set_width(ui_lightonicon2, LV_SIZE_CONTENT); /// 53
  lv_obj_set_height(ui_lightonicon2, LV_SIZE_CONTENT);  /// 76
  lv_obj_set_x(ui_lightonicon2, 1);
  lv_obj_set_y(ui_lightonicon2, -1);
  lv_obj_set_align(ui_lightonicon2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_lightonicon2,
                  LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_lightonicon2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_lightonicon2, 150);

  ui_historylb2 = lv_label_create(ui_inforpanel2);
  lv_obj_set_width(ui_historylb2, 90);
  lv_obj_set_height(ui_historylb2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_historylb2, 103);
  lv_obj_set_y(ui_historylb2, 19);
  lv_obj_set_align(ui_historylb2, LV_ALIGN_CENTER);
  lv_label_set_text(ui_historylb2, "");
  lv_obj_set_style_text_color(ui_historylb2,
                              lv_color_hex(0xF64C07),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_historylb2, 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_historylb2,
                              LV_TEXT_ALIGN_LEFT,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_historylb2,
                             &lv_font_montserrat_10,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_deviceinforlb2 = lv_label_create(ui_inforpanel2);
  lv_obj_set_width(ui_deviceinforlb2, 69);
  lv_obj_set_height(ui_deviceinforlb2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_deviceinforlb2, 97);
  lv_obj_set_y(ui_deviceinforlb2, -3);
  lv_obj_set_align(ui_deviceinforlb2, LV_ALIGN_CENTER);
  lv_label_set_text(ui_deviceinforlb2, "");
  lv_obj_set_style_text_color(ui_deviceinforlb2,
                              lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_deviceinforlb2,
                            255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_deviceinforlb2,
                              LV_TEXT_ALIGN_CENTER,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_deviceinforlb2,
                             &lv_font_montserrat_20,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_inforpanel3 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_inforpanel3, 310);
  lv_obj_set_height(ui_inforpanel3, 60);
  lv_obj_set_x(ui_inforpanel3, 0);
  lv_obj_set_y(ui_inforpanel3, 40);
  lv_obj_set_align(ui_inforpanel3, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_inforpanel3, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_add_flag(ui_inforpanel3, LV_OBJ_FLAG_HIDDEN);
  lv_obj_set_style_bg_color(ui_inforpanel3,
                            lv_color_hex(0x0067FF),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_inforpanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_inforpanel3,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_border_side(ui_inforpanel3,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

  ui_devicenamelb3 = lv_label_create(ui_inforpanel3);
  lv_obj_set_width(ui_devicenamelb3, 160);
  lv_obj_set_height(ui_devicenamelb3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_devicenamelb3, -70);
  lv_obj_set_y(ui_devicenamelb3, 10);
  lv_obj_set_align(ui_devicenamelb3, LV_ALIGN_CENTER);
  lv_label_set_text(ui_devicenamelb3, "");
  lv_obj_set_style_text_color(ui_devicenamelb3,
                              lv_color_hex(0xFBE008),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_devicenamelb3,
                            255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_devicenamelb3,
                             &lv_font_montserrat_16,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_maclb3 = lv_label_create(ui_inforpanel3);
  lv_obj_set_width(ui_maclb3, 160);
  lv_obj_set_height(ui_maclb3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_maclb3, -70);
  lv_obj_set_y(ui_maclb3, -13);
  lv_obj_set_align(ui_maclb3, LV_ALIGN_CENTER);
  lv_label_set_text(ui_maclb3, "");
  lv_obj_set_style_text_color(ui_maclb3,
                              lv_color_hex(0x00FA28),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_maclb3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_maclb3,
                             &lv_font_montserrat_16,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_removeicon3 = lv_img_create(ui_inforpanel3);
  lv_img_set_src(ui_removeicon3, &ui_img_rm_icon_png);
  lv_obj_set_width(ui_removeicon3, LV_SIZE_CONTENT); /// 118
  lv_obj_set_height(ui_removeicon3, LV_SIZE_CONTENT);  /// 119
  lv_obj_set_x(ui_removeicon3, 142);
  lv_obj_set_y(ui_removeicon3, -18);
  lv_obj_set_align(ui_removeicon3, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_removeicon3,
                  LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE
                  | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_removeicon3, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_removeicon3, 40);

  ui_deviceiconpn3 = lv_obj_create(ui_inforpanel3);
  lv_obj_set_width(ui_deviceiconpn3, 45);
  lv_obj_set_height(ui_deviceiconpn3, 50);
  lv_obj_set_x(ui_deviceiconpn3, 28);
  lv_obj_set_y(ui_deviceiconpn3, -1);
  lv_obj_set_align(ui_deviceiconpn3, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_deviceiconpn3, LV_OBJ_FLAG_HIDDEN);   /// Flags
  lv_obj_clear_flag(ui_deviceiconpn3, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_bg_color(ui_deviceiconpn3,
                            lv_color_hex(0x0067FF),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_deviceiconpn3, 255,
                          LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_deviceiconpn3,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_lightofficon3 = lv_img_create(ui_deviceiconpn3);
  lv_img_set_src(ui_lightofficon3, &ui_img_light_off_icon_png);
  lv_obj_set_width(ui_lightofficon3, LV_SIZE_CONTENT); /// 63
  lv_obj_set_height(ui_lightofficon3, LV_SIZE_CONTENT);  /// 80
  lv_obj_set_x(ui_lightofficon3, 1);
  lv_obj_set_y(ui_lightofficon3, 0);
  lv_obj_set_align(ui_lightofficon3, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_lightofficon3,
                  LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_lightofficon3, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_lightofficon3, 150);

  ui_tempicon3 = lv_img_create(ui_deviceiconpn3);
  lv_img_set_src(ui_tempicon3, &ui_img_temperature_icon_png);
  lv_obj_set_width(ui_tempicon3, LV_SIZE_CONTENT); /// 128
  lv_obj_set_height(ui_tempicon3, LV_SIZE_CONTENT);  /// 129
  lv_obj_set_x(ui_tempicon3, -1);
  lv_obj_set_y(ui_tempicon3, -1);
  lv_obj_set_align(ui_tempicon3, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_tempicon3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_tempicon3, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_tempicon3, 80);

  ui_butofficon3 = lv_img_create(ui_deviceiconpn3);
  lv_img_set_src(ui_butofficon3, &ui_img_button_off_ic_1_png);
  lv_obj_set_width(ui_butofficon3, LV_SIZE_CONTENT); /// 42
  lv_obj_set_height(ui_butofficon3, LV_SIZE_CONTENT);  /// 42
  lv_obj_set_align(ui_butofficon3, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_butofficon3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_butofficon3, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  ui_butonicon3 = lv_img_create(ui_deviceiconpn3);
  lv_img_set_src(ui_butonicon3, &ui_img_button_on_ic_1_png);
  lv_obj_set_width(ui_butonicon3, LV_SIZE_CONTENT); /// 43
  lv_obj_set_height(ui_butonicon3, LV_SIZE_CONTENT);  /// 40
  lv_obj_set_x(ui_butonicon3, -1);
  lv_obj_set_y(ui_butonicon3, 1);
  lv_obj_set_align(ui_butonicon3, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_butonicon3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_butonicon3, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  ui_lightonicon3 = lv_img_create(ui_deviceiconpn3);
  lv_img_set_src(ui_lightonicon3, &ui_img_light_on_icon_1_png);
  lv_obj_set_width(ui_lightonicon3, LV_SIZE_CONTENT); /// 53
  lv_obj_set_height(ui_lightonicon3, LV_SIZE_CONTENT);  /// 76
  lv_obj_set_x(ui_lightonicon3, 1);
  lv_obj_set_y(ui_lightonicon3, -1);
  lv_obj_set_align(ui_lightonicon3, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_lightonicon3,
                  LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_lightonicon3, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_lightonicon3, 150);

  ui_historylb3 = lv_label_create(ui_inforpanel3);
  lv_obj_set_width(ui_historylb3, 90);
  lv_obj_set_height(ui_historylb3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_historylb3, 103);
  lv_obj_set_y(ui_historylb3, 19);
  lv_obj_set_align(ui_historylb3, LV_ALIGN_CENTER);
  lv_label_set_text(ui_historylb3, "");
  lv_obj_set_style_text_color(ui_historylb3,
                              lv_color_hex(0xF64C07),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_historylb3, 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_historylb3,
                              LV_TEXT_ALIGN_LEFT,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_historylb3,
                             &lv_font_montserrat_10,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_deviceinforlb3 = lv_label_create(ui_inforpanel3);
  lv_obj_set_width(ui_deviceinforlb3, 69);
  lv_obj_set_height(ui_deviceinforlb3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_deviceinforlb3, 97);
  lv_obj_set_y(ui_deviceinforlb3, -3);
  lv_obj_set_align(ui_deviceinforlb3, LV_ALIGN_CENTER);
  lv_label_set_text(ui_deviceinforlb3, "");
  lv_obj_set_style_text_color(ui_deviceinforlb3,
                              lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_deviceinforlb3,
                            255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_deviceinforlb3,
                              LV_TEXT_ALIGN_CENTER,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_deviceinforlb3,
                             &lv_font_montserrat_20,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_inforpanel4 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_inforpanel4, 310);
  lv_obj_set_height(ui_inforpanel4, 60);
  lv_obj_set_x(ui_inforpanel4, 0);
  lv_obj_set_y(ui_inforpanel4, 105);
  lv_obj_set_align(ui_inforpanel4, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_inforpanel4, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_add_flag(ui_inforpanel4, LV_OBJ_FLAG_HIDDEN);
  lv_obj_set_style_bg_color(ui_inforpanel4,
                            lv_color_hex(0x0047FB),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_inforpanel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_inforpanel4,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_border_side(ui_inforpanel4,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

  ui_maclb4 = lv_label_create(ui_inforpanel4);
  lv_obj_set_width(ui_maclb4, 160);
  lv_obj_set_height(ui_maclb4, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_maclb4, -70);
  lv_obj_set_y(ui_maclb4, -13);
  lv_obj_set_align(ui_maclb4, LV_ALIGN_CENTER);
  lv_label_set_text(ui_maclb4, "");
  lv_obj_set_style_text_color(ui_maclb4,
                              lv_color_hex(0x00FA28),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_maclb4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_maclb4,
                             &lv_font_montserrat_16,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_devicenamelb4 = lv_label_create(ui_inforpanel4);
  lv_obj_set_width(ui_devicenamelb4, 160);
  lv_obj_set_height(ui_devicenamelb4, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_devicenamelb4, -70);
  lv_obj_set_y(ui_devicenamelb4, 10);
  lv_obj_set_align(ui_devicenamelb4, LV_ALIGN_CENTER);
  lv_label_set_text(ui_devicenamelb4, "");
  lv_obj_set_style_text_color(ui_devicenamelb4,
                              lv_color_hex(0xFBE008),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_devicenamelb4,
                            255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_devicenamelb4,
                             &lv_font_montserrat_16,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_removeicon4 = lv_img_create(ui_inforpanel4);
  lv_img_set_src(ui_removeicon4, &ui_img_rm_icon_png);
  lv_obj_set_width(ui_removeicon4, LV_SIZE_CONTENT); /// 118
  lv_obj_set_height(ui_removeicon4, LV_SIZE_CONTENT);  /// 119
  lv_obj_set_x(ui_removeicon4, 142);
  lv_obj_set_y(ui_removeicon4, -18);
  lv_obj_set_align(ui_removeicon4, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_removeicon4,
                  LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE
                  | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_removeicon4, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_removeicon4, 40);

  ui_deviceiconpn4 = lv_obj_create(ui_inforpanel4);
  lv_obj_set_width(ui_deviceiconpn4, 45);
  lv_obj_set_height(ui_deviceiconpn4, 50);
  lv_obj_set_x(ui_deviceiconpn4, 28);
  lv_obj_set_y(ui_deviceiconpn4, -1);
  lv_obj_set_align(ui_deviceiconpn4, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_deviceiconpn4, LV_OBJ_FLAG_HIDDEN);   /// Flags
  lv_obj_clear_flag(ui_deviceiconpn4, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_bg_color(ui_deviceiconpn4,
                            lv_color_hex(0x0047FB),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_deviceiconpn4, 255,
                          LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_deviceiconpn4,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_lightofficon4 = lv_img_create(ui_deviceiconpn4);
  lv_img_set_src(ui_lightofficon4, &ui_img_light_off_icon_png);
  lv_obj_set_width(ui_lightofficon4, LV_SIZE_CONTENT); /// 63
  lv_obj_set_height(ui_lightofficon4, LV_SIZE_CONTENT);  /// 80
  lv_obj_set_x(ui_lightofficon4, 1);
  lv_obj_set_y(ui_lightofficon4, 0);
  lv_obj_set_align(ui_lightofficon4, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_lightofficon4,
                  LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);

  lv_obj_clear_flag(ui_lightofficon4, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_lightofficon4, 150);

  ui_tempicon4 = lv_img_create(ui_deviceiconpn4);
  lv_img_set_src(ui_tempicon4, &ui_img_temperature_icon_png);
  lv_obj_set_width(ui_tempicon4, LV_SIZE_CONTENT); /// 128
  lv_obj_set_height(ui_tempicon4, LV_SIZE_CONTENT);  /// 129
  lv_obj_set_x(ui_tempicon4, -1);
  lv_obj_set_y(ui_tempicon4, -1);
  lv_obj_set_align(ui_tempicon4, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_tempicon4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);

  lv_obj_clear_flag(ui_tempicon4, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_tempicon4, 80);

  ui_butofficon4 = lv_img_create(ui_deviceiconpn4);
  lv_img_set_src(ui_butofficon4, &ui_img_button_off_ic_1_png);
  lv_obj_set_width(ui_butofficon4, LV_SIZE_CONTENT); /// 42
  lv_obj_set_height(ui_butofficon4, LV_SIZE_CONTENT);  /// 42
  lv_obj_set_align(ui_butofficon4, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_butofficon4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);

  lv_obj_clear_flag(ui_butofficon4, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  ui_butonicon4 = lv_img_create(ui_deviceiconpn4);
  lv_img_set_src(ui_butonicon4, &ui_img_button_on_ic_1_png);
  lv_obj_set_width(ui_butonicon4, LV_SIZE_CONTENT); /// 43
  lv_obj_set_height(ui_butonicon4, LV_SIZE_CONTENT);  /// 40
  lv_obj_set_x(ui_butonicon4, -1);
  lv_obj_set_y(ui_butonicon4, 1);
  lv_obj_set_align(ui_butonicon4, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_butonicon4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);

  lv_obj_clear_flag(ui_butonicon4, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  ui_lightonicon4 = lv_img_create(ui_deviceiconpn4);
  lv_img_set_src(ui_lightonicon4, &ui_img_light_on_icon_1_png);
  lv_obj_set_width(ui_lightonicon4, LV_SIZE_CONTENT); /// 53
  lv_obj_set_height(ui_lightonicon4, LV_SIZE_CONTENT);  /// 76
  lv_obj_set_x(ui_lightonicon4, 1);
  lv_obj_set_y(ui_lightonicon4, -1);
  lv_obj_set_align(ui_lightonicon4, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_lightonicon4,
                  LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);

  lv_obj_clear_flag(ui_lightonicon4, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_lightonicon4, 150);

  ui_historylb4 = lv_label_create(ui_inforpanel4);
  lv_obj_set_width(ui_historylb4, 90);
  lv_obj_set_height(ui_historylb4, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_historylb4, 103);
  lv_obj_set_y(ui_historylb4, 19);
  lv_obj_set_align(ui_historylb4, LV_ALIGN_CENTER);
  lv_label_set_text(ui_historylb4, "");
  lv_obj_set_style_text_color(ui_historylb4,
                              lv_color_hex(0xF64C07),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_historylb4, 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_historylb4,
                              LV_TEXT_ALIGN_LEFT,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_historylb4,
                             &lv_font_montserrat_10,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_deviceinforlb4 = lv_label_create(ui_inforpanel4);
  lv_obj_set_width(ui_deviceinforlb4, 69);
  lv_obj_set_height(ui_deviceinforlb4, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_deviceinforlb4, 97);
  lv_obj_set_y(ui_deviceinforlb4, -3);
  lv_obj_set_align(ui_deviceinforlb4, LV_ALIGN_CENTER);
  lv_label_set_text(ui_deviceinforlb4, "");
  lv_obj_set_style_text_color(ui_deviceinforlb4,
                              lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_deviceinforlb4,
                            255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_deviceinforlb4,
                              LV_TEXT_ALIGN_CENTER,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_deviceinforlb4,
                             &lv_font_montserrat_20,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_inforpanel5 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_inforpanel5, 310);
  lv_obj_set_height(ui_inforpanel5, 60);
  lv_obj_set_x(ui_inforpanel5, -1);
  lv_obj_set_y(ui_inforpanel5, 170);
  lv_obj_set_align(ui_inforpanel5, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_inforpanel5, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_add_flag(ui_inforpanel5, LV_OBJ_FLAG_HIDDEN);
  lv_obj_set_style_bg_color(ui_inforpanel5,
                            lv_color_hex(0x1510F0),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_inforpanel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_inforpanel5,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_border_side(ui_inforpanel5,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

  ui_devicenamelb5 = lv_label_create(ui_inforpanel5);
  lv_obj_set_width(ui_devicenamelb5, 160);
  lv_obj_set_height(ui_devicenamelb5, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_devicenamelb5, -70);
  lv_obj_set_y(ui_devicenamelb5, 10);
  lv_obj_set_align(ui_devicenamelb5, LV_ALIGN_CENTER);
  lv_label_set_text(ui_devicenamelb5, "");
  lv_obj_set_style_text_color(ui_devicenamelb5,
                              lv_color_hex(0xFBE008),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_devicenamelb5,
                            255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_devicenamelb5,
                             &lv_font_montserrat_16,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_maclb5 = lv_label_create(ui_inforpanel5);
  lv_obj_set_width(ui_maclb5, 160);
  lv_obj_set_height(ui_maclb5, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_maclb5, -70);
  lv_obj_set_y(ui_maclb5, -13);
  lv_obj_set_align(ui_maclb5, LV_ALIGN_CENTER);
  lv_label_set_text(ui_maclb5, "");
  lv_obj_set_style_text_color(ui_maclb5,
                              lv_color_hex(0x00FA28),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_maclb5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_maclb5,
                             &lv_font_montserrat_16,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_removeicon5 = lv_img_create(ui_inforpanel5);
  lv_img_set_src(ui_removeicon5, &ui_img_rm_icon_png);
  lv_obj_set_width(ui_removeicon5, LV_SIZE_CONTENT); /// 118
  lv_obj_set_height(ui_removeicon5, LV_SIZE_CONTENT);  /// 119
  lv_obj_set_x(ui_removeicon5, 142);
  lv_obj_set_y(ui_removeicon5, -18);
  lv_obj_set_align(ui_removeicon5, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_removeicon5,
                  LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE
                  | LV_OBJ_FLAG_ADV_HITTEST);

  lv_obj_clear_flag(ui_removeicon5, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_removeicon5, 40);

  ui_deviceiconpn5 = lv_obj_create(ui_inforpanel5);
  lv_obj_set_width(ui_deviceiconpn5, 45);
  lv_obj_set_height(ui_deviceiconpn5, 50);
  lv_obj_set_x(ui_deviceiconpn5, 28);
  lv_obj_set_y(ui_deviceiconpn5, -1);
  lv_obj_set_align(ui_deviceiconpn5, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_deviceiconpn5, LV_OBJ_FLAG_HIDDEN);   /// Flags
  lv_obj_clear_flag(ui_deviceiconpn5, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_bg_color(ui_deviceiconpn5,
                            lv_color_hex(0x1510F0),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_deviceiconpn5, 255,
                          LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_deviceiconpn5,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_lightofficon5 = lv_img_create(ui_deviceiconpn5);
  lv_img_set_src(ui_lightofficon5, &ui_img_light_off_icon_png);
  lv_obj_set_width(ui_lightofficon5, LV_SIZE_CONTENT); /// 63
  lv_obj_set_height(ui_lightofficon5, LV_SIZE_CONTENT);  /// 80
  lv_obj_set_x(ui_lightofficon5, 1);
  lv_obj_set_y(ui_lightofficon5, 0);
  lv_obj_set_align(ui_lightofficon5, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_lightofficon5,
                  LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_lightofficon5, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_lightofficon5, 150);

  ui_tempicon5 = lv_img_create(ui_deviceiconpn5);
  lv_img_set_src(ui_tempicon5, &ui_img_temperature_icon_png);
  lv_obj_set_width(ui_tempicon5, LV_SIZE_CONTENT); /// 128
  lv_obj_set_height(ui_tempicon5, LV_SIZE_CONTENT);  /// 129
  lv_obj_set_x(ui_tempicon5, -1);
  lv_obj_set_y(ui_tempicon5, -1);
  lv_obj_set_align(ui_tempicon5, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_tempicon5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_tempicon5, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_tempicon5, 80);

  ui_butofficon5 = lv_img_create(ui_deviceiconpn5);
  lv_img_set_src(ui_butofficon5, &ui_img_button_off_ic_1_png);
  lv_obj_set_width(ui_butofficon5, LV_SIZE_CONTENT); /// 42
  lv_obj_set_height(ui_butofficon5, LV_SIZE_CONTENT);  /// 42
  lv_obj_set_align(ui_butofficon5, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_butofficon5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_butofficon5, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  ui_butonicon5 = lv_img_create(ui_deviceiconpn5);
  lv_img_set_src(ui_butonicon5, &ui_img_button_on_ic_1_png);
  lv_obj_set_width(ui_butonicon5, LV_SIZE_CONTENT); /// 43
  lv_obj_set_height(ui_butonicon5, LV_SIZE_CONTENT);  /// 40
  lv_obj_set_x(ui_butonicon5, -1);
  lv_obj_set_y(ui_butonicon5, 1);
  lv_obj_set_align(ui_butonicon5, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_butonicon5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_butonicon5, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  ui_lightonicon5 = lv_img_create(ui_deviceiconpn5);
  lv_img_set_src(ui_lightonicon5, &ui_img_light_on_icon_1_png);
  lv_obj_set_width(ui_lightonicon5, LV_SIZE_CONTENT); /// 53
  lv_obj_set_height(ui_lightonicon5, LV_SIZE_CONTENT);  /// 76
  lv_obj_set_x(ui_lightonicon5, 1);
  lv_obj_set_y(ui_lightonicon5, -1);
  lv_obj_set_align(ui_lightonicon5, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_lightonicon5,
                  LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_lightonicon5, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_lightonicon5, 150);

  ui_historylb5 = lv_label_create(ui_inforpanel5);
  lv_obj_set_width(ui_historylb5, 90);
  lv_obj_set_height(ui_historylb5, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_historylb5, 103);
  lv_obj_set_y(ui_historylb5, 19);
  lv_obj_set_align(ui_historylb5, LV_ALIGN_CENTER);
  lv_label_set_text(ui_historylb5, "");
  lv_obj_set_style_text_color(ui_historylb5,
                              lv_color_hex(0xF64C07),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_historylb5, 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_historylb5,
                              LV_TEXT_ALIGN_LEFT,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_historylb5,
                             &lv_font_montserrat_10,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_deviceinforlb5 = lv_label_create(ui_inforpanel5);
  lv_obj_set_width(ui_deviceinforlb5, 69);
  lv_obj_set_height(ui_deviceinforlb5, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_deviceinforlb5, 97);
  lv_obj_set_y(ui_deviceinforlb5, -3);
  lv_obj_set_align(ui_deviceinforlb5, LV_ALIGN_CENTER);
  lv_label_set_text(ui_deviceinforlb5, "");
  lv_obj_set_style_text_color(ui_deviceinforlb5,
                              lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_deviceinforlb5,
                            255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_deviceinforlb5,
                              LV_TEXT_ALIGN_CENTER,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_deviceinforlb5,
                             &lv_font_montserrat_20,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_settingpn = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_settingpn, 58);
  lv_obj_set_height(ui_settingpn, 35);
  lv_obj_set_x(ui_settingpn, 0);
  lv_obj_set_y(ui_settingpn, 219);
  lv_obj_set_align(ui_settingpn, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_settingpn, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_radius(ui_settingpn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_settingpn,
                            lv_color_hex(0x00A8F7),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_settingpn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_settingpn,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_settingicon = lv_img_create(ui_settingpn);
  lv_img_set_src(ui_settingicon, &ui_img_setting_icon_png);
  lv_obj_set_width(ui_settingicon, LV_SIZE_CONTENT); /// 118
  lv_obj_set_height(ui_settingicon, LV_SIZE_CONTENT);  /// 122
  lv_obj_set_align(ui_settingicon, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_settingicon, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_clear_flag(ui_settingicon, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_settingicon, 50);

  ui_tickpn0 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_tickpn0, 58);
  lv_obj_set_height(ui_tickpn0, 35);
  lv_obj_set_x(ui_tickpn0, -45);
  lv_obj_set_y(ui_tickpn0, 219);
  lv_obj_set_align(ui_tickpn0, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_tickpn0, LV_OBJ_FLAG_HIDDEN);   /// Flags
  lv_obj_clear_flag(ui_tickpn0, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_radius(ui_tickpn0, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_tickpn0,
                            lv_color_hex(0x9CF2AC),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_tickpn0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_tickpn0,
                               LV_BORDER_SIDE_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_tickicon0 = lv_img_create(ui_tickpn0);
  lv_img_set_src(ui_tickicon0, &ui_img_tick_icon_png);
  lv_obj_set_width(ui_tickicon0, LV_SIZE_CONTENT); /// 87
  lv_obj_set_height(ui_tickicon0, LV_SIZE_CONTENT);  /// 87
  lv_obj_set_align(ui_tickicon0, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_tickicon0, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_clear_flag(ui_tickicon0, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_tickicon0, 75);

  lv_obj_add_event_cb(ui_removeicon0, ui_event_removeicon0, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_removeicon1, ui_event_removeicon1, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_removeicon2, ui_event_removeicon2, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_removeicon3, ui_event_removeicon3, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_removeicon4, ui_event_removeicon4, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_removeicon5, ui_event_removeicon5, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_settingpn, ui_event_settingpn, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_tickpn0, ui_event_tickpn0, LV_EVENT_ALL, NULL);
}
