/***************************************************************************//**
 * @file client_oled_app.c
 * @brief client oled application source file.
 *******************************************************************************
 * # License
 * <b>Copyright 2022 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * SPDX-License-Identifier: Zlib
 *
 * The licensor of this software is Silicon Laboratories Inc.
 *
 * This software is provided \'as-is\', without any express or implied
 * warranty. In no event will the authors be held liable for any damages
 * arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented{} you must not
 *    claim that you wrote the original software. If you use this software
 *    in a product, an acknowledgment in the product documentation would be
 *    appreciated but is not required.
 * 2. Altered source versions must be plainly marked as such, and must not be
 *    misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 *
 *******************************************************************************
 * # Experimental Quality
 * This code has not been formally tested and is provided as-is. It is not
 * suitable for production environments. In addition, this code will not be
 * maintained and there may be no bug maintenance planned for these resources.
 * Silicon Labs may update projects from time to time.
 ******************************************************************************/
#include <stdio.h>
#include <string.h>
#include "app_log.h"
#include "client_oled_app.h"
#include "app_assert.h"
#include "sl_sleeptimer.h"

/* This array is generated by LCDAssistant Tool. A image with bitmap format can
 * use this tool to convert to code.
 * To draw an image or custom bitmaps on the oled, the glib_draw_bmp()
 * function can be used.
 * */
static const unsigned char silicon_labs_logo_64x23[] = {
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
  0x00, 0x00, 0x00, 0x80, 0xff, 0x1f, 0x00, 0x1e, 0x00, 0x00, 0x00, 0xf0,
  0xff, 0x7f, 0x00, 0x3e, 0x00, 0x00, 0x00, 0xfe, 0xff, 0x7f, 0x00, 0x7f,
  0x00, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x80, 0x7f, 0x00, 0x06, 0x80, 0xff,
  0xff, 0xff, 0xe0, 0xff, 0x80, 0x03, 0xc0, 0xff, 0x01, 0xf8, 0xff, 0x7f,
  0xe0, 0x01, 0xc0, 0x03, 0x00, 0x00, 0xfe, 0x7f, 0xf0, 0x01, 0x00, 0x01,
  0x00, 0x00, 0xf8, 0x3f, 0xf8, 0x03, 0x00, 0xf0, 0x07, 0x00, 0xe0, 0x3f,
  0xfc, 0x03, 0x00, 0x00, 0x20, 0x00, 0xe0, 0x1f, 0xfe, 0x0f, 0x00, 0x00,
  0xc0, 0x00, 0xe0, 0x07, 0xfe, 0xff, 0x00, 0x00, 0xfc, 0x00, 0xe0, 0x03,
  0xff, 0xc3, 0xff, 0xff, 0xff, 0x00, 0xf0, 0x00, 0x7e, 0x00, 0xfe, 0xff,
  0x7f, 0x00, 0x38, 0x00, 0x3e, 0x00, 0xff, 0xff, 0x3f, 0x00, 0x0c, 0x00,
  0x1c, 0x80, 0xff, 0xff, 0x0f, 0x00, 0x00, 0x00, 0x18, 0x00, 0xff, 0xff,
  0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf8, 0x1f, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00
};

static glib_context_t glib_context;

// Display runtime data
static disconnected_display_data_t display;

// periodic timer callback
void disconnected_simple_timer_display_cb(app_timer_t *handle,
                                          void *data);

/***************************************************************************//**
 * Client Oled Application Initialize.
 ******************************************************************************/
void client_oled_app_init(void)
{
  if (ssd1306_init(sl_i2cspm_qwiic) == SL_STATUS_OK) {
    app_log("Sparkfun Oled Init Done\r\n");
  } else {
    app_log("Sparkfun Oled Init Failed\r\n");
  }

  /* Initialize the display */
  glib_init(&glib_context);

  glib_context.bg_color = GLIB_BLACK;
  glib_context.text_color = GLIB_WHITE;
  display.max_char_per_line = 10;

  /* Fill lcd with background color */
  glib_clear(&glib_context);
  glib_draw_xbitmap(&glib_context,
                    0, 10, silicon_labs_logo_64x23,
                    64, 23, GLIB_WHITE);
  glib_update_display();
  sl_sleeptimer_delay_millisecond(1000);

  /* Fill lcd with background color */
  glib_clear(&glib_context);
}

/***************************************************************************//**
 * Client Oled Application Display.
 ******************************************************************************/
void client_oled_app_radiation_display(float radiation_value)
{
  char number_str[11];
  int len;
  int32_t data_x_start;

  glib_clear(&glib_context);
  app_timer_stop(&display.timer_handle);

  /* Use Narrow font */
  glib_set_font(&glib_context, NULL);
  glib_draw_string(&glib_context, "RADIATION", 5, 0);
  glib_draw_line(&glib_context, 0, 11, 63, 11, GLIB_WHITE);

  // Display radiation value
  len = snprintf(number_str, sizeof(number_str), "%.1fuSv/h", radiation_value);
  data_x_start = (64 - len * 5 - (len - 1)) / 2;
  glib_set_font(&glib_context, (glib_gfx_font_t *) &glib_font_4x7);
  glib_draw_string(&glib_context, number_str, data_x_start, 26);
  glib_set_font(&glib_context, NULL);
  glib_draw_string(&glib_context, "CONNECTED", 5, 39);

  glib_draw_line(&glib_context, 0, 35, 63, 35, GLIB_WHITE);
  glib_update_display();
}

/***************************************************************************//**
 * Client Oled Application Disconnected Display.
 ******************************************************************************/
void client_oled_app_disconnected_display(void)
{
  glib_clear(&glib_context);

  /* Use Narrow font */
  glib_set_font(&glib_context, NULL);
  glib_draw_string(&glib_context, "RADIATION", 5, 0);
  glib_draw_line(&glib_context, 0, 11, 63, 11, GLIB_WHITE);

  glib_set_font(&glib_context, (glib_gfx_font_t *) &glib_font_4x7);
  glib_draw_string(&glib_context, "           ", 0, 26);
  glib_draw_string(&glib_context, "---", 25, 24);

  glib_draw_line(&glib_context, 0, 35, 63, 35, GLIB_WHITE);

  glib_set_font(&glib_context, NULL);
  strcpy((char *) display.param_text, "DISCONNECTED");
  display.first_letter = display.param_text;
  display.text_length = strlen((char *) display.param_text);
  glib_update_display();

  sl_status_t sc = app_timer_start(&display.timer_handle,
                                   300,
                                   disconnected_simple_timer_display_cb,
                                   (void *)NULL,
                                   true);
  app_assert_status_f(sc, "Failed to start timer\r\n");
}

/***************************************************************************//**
 * Client Oled Application Configuration Mode Display.
 ******************************************************************************/
void client_oled_app_config_mode_display(void)
{
  glib_clear(&glib_context);

  // Display Configuration Mode.
  glib_set_font(&glib_context, NULL);
  glib_draw_string(&glib_context, "CONFIG", 14, 15);
  glib_draw_string(&glib_context, "MODE", 20, 28);
  glib_update_display();
}

static void display_set_paramline_next_text(uint8_t *text_buffer)
{
  uint8_t txt_length = strlen((char *) display.first_letter);
  uint8_t txt_remainder_length = 0;

  if (txt_length > display.max_char_per_line) {
    txt_length = display.max_char_per_line;
  } else {
    txt_remainder_length = display.max_char_per_line
                           - txt_length;
  }

  // Copy letters starting from first_letter pointer
  memcpy(text_buffer, display.first_letter, txt_length);

  // Copy remaining letters if any
  if (0 != txt_remainder_length) {
    // Append a whitespace between the last and first characters
    text_buffer[txt_length] = ' ';
    memcpy(&text_buffer[txt_length + 1], display.param_text,
           txt_remainder_length);
  }

  // Advance first letter pointer
  display.first_letter++;

  // If it points to the tailing char then
  if (*display.first_letter == '\0') {
    display.first_letter = display.param_text;
  }
  text_buffer[display.max_char_per_line] = '\0';
}

/***************************************************************************//**
 * Disconnected timer callbacks
 ******************************************************************************/
void disconnected_simple_timer_display_cb(app_timer_t *handle,
                                          void *data)
{
  (void)data;
  (void)handle;
  uint8_t param_text_buffer[display.max_char_per_line + 1];

  display_set_paramline_next_text(param_text_buffer);
  glib_draw_string(&glib_context, (char *) param_text_buffer, 1, 39);
  // Update display
  glib_update_display();
}
