/***************************************************************************//**
 * @file co_client_oled_app.c
 * @brief co client oled application source file.
 *******************************************************************************
 * # License
 * <b>Copyright 2022 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * SPDX-License-Identifier: Zlib
 *
 * The licensor of this software is Silicon Laboratories Inc.
 *
 * This software is provided \'as-is\', without any express or implied
 * warranty. In no event will the authors be held liable for any damages
 * arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented{} you must not
 *    claim that you wrote the original software. If you use this software
 *    in a product, an acknowledgment in the product documentation would be
 *    appreciated but is not required.
 * 2. Altered source versions must be plainly marked as such, and must not be
 *    misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 *
 *******************************************************************************
 * # Experimental Quality
 * This code has not been formally tested and is provided as-is. It is not
 * suitable for production environments. In addition, this code will not be
 * maintained and there may be no bug maintenance planned for these resources.
 * Silicon Labs may update projects from time to time.
 ******************************************************************************/
#include "co_client_oled.h"
#include "sl_i2cspm_instances.h"
#include "glib.h"
#include "glib_font.h"
#include "micro_oled_ssd1306.h"
#include <stdio.h>
#include <string.h>
#include "app_log.h"
#include "app_assert.h"
#include "sl_sleeptimer.h"

/* This array is generated by LCDAssistant Tool. A image with bitmap format can
 * use this tool to convert to code.
 * To draw an image or custom bitmaps on the oled, the glib_draw_bmp()
 * function can be used.
 * */
static const unsigned char silicon_labs_logo_64x23[] = {
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
  0x00, 0x00, 0x00, 0x80, 0xff, 0x1f, 0x00, 0x1e, 0x00, 0x00, 0x00, 0xf0,
  0xff, 0x7f, 0x00, 0x3e, 0x00, 0x00, 0x00, 0xfe, 0xff, 0x7f, 0x00, 0x7f,
  0x00, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x80, 0x7f, 0x00, 0x06, 0x80, 0xff,
  0xff, 0xff, 0xe0, 0xff, 0x80, 0x03, 0xc0, 0xff, 0x01, 0xf8, 0xff, 0x7f,
  0xe0, 0x01, 0xc0, 0x03, 0x00, 0x00, 0xfe, 0x7f, 0xf0, 0x01, 0x00, 0x01,
  0x00, 0x00, 0xf8, 0x3f, 0xf8, 0x03, 0x00, 0xf0, 0x07, 0x00, 0xe0, 0x3f,
  0xfc, 0x03, 0x00, 0x00, 0x20, 0x00, 0xe0, 0x1f, 0xfe, 0x0f, 0x00, 0x00,
  0xc0, 0x00, 0xe0, 0x07, 0xfe, 0xff, 0x00, 0x00, 0xfc, 0x00, 0xe0, 0x03,
  0xff, 0xc3, 0xff, 0xff, 0xff, 0x00, 0xf0, 0x00, 0x7e, 0x00, 0xfe, 0xff,
  0x7f, 0x00, 0x38, 0x00, 0x3e, 0x00, 0xff, 0xff, 0x3f, 0x00, 0x0c, 0x00,
  0x1c, 0x80, 0xff, 0xff, 0x0f, 0x00, 0x00, 0x00, 0x18, 0x00, 0xff, 0xff,
  0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf8, 0x1f, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00
};

static glib_context_t glib_context;

/***************************************************************************//**
 * Client Oled Application Initialize.
 ******************************************************************************/
void client_oled_app_init(void)
{
  if (ssd1306_init(sl_i2cspm_qwiic) == SL_STATUS_OK) {
    app_log("Sparkfun Oled Init Done\r\n");
  } else {
    app_log("Sparkfun Oled Init Failed\r\n");
  }

  /* Initialize the display */
  glib_init(&glib_context);

  glib_context.bg_color = GLIB_BLACK;
  glib_context.text_color = GLIB_WHITE;

  /* Fill lcd with background color */
  glib_clear(&glib_context);
  glib_draw_xbitmap(&glib_context,
                    0, 10, silicon_labs_logo_64x23,
                    64, 23, GLIB_WHITE);
  glib_update_display();
  sl_sleeptimer_delay_millisecond(1000);

  /* Fill lcd with background color */
  glib_clear(&glib_context);
}

/***************************************************************************//**
 * Client Oled Application Display.
 ******************************************************************************/
void client_oled_app_update_co_level_screen(uint32_t ppm_value,
                                            uint32_t threshold_value)
{
  char number_str[11];
  int len;
  int32_t data_x_start;

  glib_clear(&glib_context);

  /* Use Narrow font */
  glib_set_font(&glib_context, NULL);
  glib_draw_string(&glib_context, "CO LEVEL", 10, 0);
  glib_draw_line(&glib_context, 0, 11, 63, 11, GLIB_WHITE);

  // Display radiation value
  len = snprintf(number_str, sizeof(number_str), "%ld ppm", ppm_value);
  glib_draw_string(&glib_context, number_str, 15, 18);

  len = snprintf(number_str, sizeof(number_str), "[%ld ppm]", threshold_value);
  data_x_start = (64 - len * 5 - (len - 1)) / 2;
  glib_draw_string(&glib_context, number_str, data_x_start, 39);

  glib_draw_line(&glib_context, 0, 35, 63, 35, GLIB_WHITE);
  glib_update_display();
}

/***************************************************************************//**
 * Client Oled Application Update Threshold Screen
 ******************************************************************************/
void client_oled_app_update_threshold_screen(uint32_t threshold,
                                             uint8_t alarm_status)
{
  char number_str[11];

  glib_clear(&glib_context);

  /* Use Narrow font */
  glib_set_font(&glib_context, NULL);
  glib_draw_string(&glib_context, "THRESHOLD", 6, 0);
  glib_draw_line(&glib_context, 0, 11, 63, 11, GLIB_WHITE);

  // Display radiation value
  snprintf(number_str, sizeof(number_str), "%ld ppm", threshold);
  glib_draw_string(&glib_context, number_str, 15, 18);

  snprintf(number_str,
           sizeof(number_str),
           "ALARM: %s",
           alarm_status == 1? "ON":"OFF");
  if (alarm_status == 0) {
    glib_draw_string(&glib_context, number_str, 3, 39);
  } else {
    glib_draw_string(&glib_context, number_str, 5, 39);
  }

  glib_draw_line(&glib_context, 0, 35, 63, 35, GLIB_WHITE);
  glib_update_display();
}
